### ISSUE TITLE
Paths with a `[` and/or `]` in them are ignored

### ISSUE THREAD

**Issue by techwraith** [standard/vscode-standard#102]
**What version of this package are you using?**
1.2.3

**What operating system, Node.js, and npm version?**
Mac OS 10.14.6

**What happened?**
I'm writing a NextJS app, and their pages directory structure uses brackets to define pretty URLs (e.g - `/[user_name]/messages` instead of `/messages?user_name=`)

This plugin seems to ignore files with brackets in the path, however. I get a "/my/path/[with]/brackets.js ignored." error in the JavaScript Standard Style output console when I save.

**What did you expect to happen?**
I expected the file to not be ignored.

**Are you willing to submit a pull request to fix this bug?**
Yes, if I knew where to start.

**Comment by apuyou** [comment]
I can confirm this. Running standard from CLI works on the same project.

This plugin is a fork of microsoft/vscode-eslint which seems to suffer from the same issue: https://github.com/microsoft/vscode-eslint/issues/977
