### ISSUE TITLE
Parsing error when trying to lint .vue files

### ISSUE THREAD

**Issue by reesewesterhoff** [standard/vscode-standard#104]
**What version of this package are you using?**
1.2.0

**What operating system, Node.js, and npm version?**
Windows 10
Node: v12.16.1
NPM: 6.13.4

**What happened?**
When trying to lint a .vue file, after adding in the specified settings from the guide to my settings.json, my .vue file shows an error at the beginning of the opening script tag that says

"Parsing error: Adjacent JSX elements must be wrapped in an enclosing tag"

![image](https://user-images.githubusercontent.com/39221548/77692803-49e7b480-6f75-11ea-85a5-ede7667377e5.png)

**What did you expect to happen?**
For the extension to lint the script tag of my .vue file. (Works fine on HTML files)

**Are you willing to submit a pull request to fix this bug?**
No

**Comment by subins2000** [comment]
Yes, this same problem happens to me too. `.vue` files are not linted therefore.

I have an HTML comment block `<!-- -->` at the beginning of the vue file and plugin only show error for it :
```
Parsing error: Unexpected token <
```

**Comment by theoludwig** [comment]
Closing as it is a duplicate of #35.
