### ISSUE TITLE
Engine auto-detection

### ISSUE THREAD

**Issue by cyrilchapon** [standard/vscode-standard#105]
**What version of this package are you using?**
Master one, built and installed manually

**What operating system, Node.js, and npm version?**
OSx 10.14.5

**What happened?**
Engine `standardx` is not auto-detected.

See https://github.com/standard/vscode-standardjs/pull/71; this is a follow up

**What did you expect to happen?**

I'd expect auto-detection of `standardx` to occur (simple project; clean package.json).

**Are you willing to submit a pull request to fix this bug?**

I could, but I need help. Not much time and never developed something for vscode

**Comment by theoludwig** [comment]
Thanks for your report! @cyrilchapon 

The feature is already implemented. :+1: 
By enabling `"standard.usePackageJson": true` in `.vscode/settings.json`, it should auto-detect the engine (`standard`, `semistandard`, `standardx` or `ts-standard`) you've installed in `devDependencies` in your `package.json`.
