### ISSUE TITLE
Publish access

### ISSUE THREAD

**Issue by LinusU** [standard/vscode-standard#107]
It would be great if some more team members from the Standard org could get publish access to the VS Code marketplace. I think that my username is `linusu@outlook.com` there ☺️ 

For now, I've tagged `1.3.0` and made a GitHub release with the .vsix file.

**Comment by chenxsan** [comment]
@LinusU 

Unfortunately there's a bug on vscode marketplace, could you email your VSID according to https://stackoverflow.com/questions/56032912/vs-marketplace-add-member-displayes-invalid-domain-error so I can contact them to add you as member? I've written an email to your outlook.

**Comment by LinusU** [comment]
Thanks for the quick response! Didn't see an email in my outlook, but sent you an email with the id from my main address: linus@folkdatorn.se

**Comment by chenxsan** [comment]
I'm afraid it would take longer because the email address vscode provides won't accept our contact now https://developercommunity.visualstudio.com/content/problem/998386/unable-to-send-email-to-vsmarketplace.html

**Comment by LinusU** [comment]
No stress, thank you for working on it!

Maybe you can publish 1.3.0 in the meantime? I think that you can download the `vsix` file from the release and upload it to the marketplace web interface ☺️

**Comment by chenxsan** [comment]
@LinusU Published.

**Comment by chenxsan** [comment]
@LinusU They've added you as owner now :) Please verify.

**Comment by LinusU** [comment]
Seems to be working 🙌 thanks!!
