### ISSUE TITLE
(react/jsx-indent) conflict with standard(indent)

### ISSUE THREAD

**Issue by josegutierro** [standard/vscode-standard#109]
![Alt Text](https://media.giphy.com/media/dW0bdf1KSsMDUeigIC/giphy.gif)

**What version of this package are you using?**
14.3.4

**What operating system, Node.js, and npm version?**
MacOS Catalina 10.15.4
Node v10.15.3
NPM 6.14.3

**What happened?**
Indent conflict with standard rule and react/jsx-indent rule

**What did you expect to happen?**
Autofix on save toggle between standard indent and react/jsx-indent

**Are you willing to submit a pull request to fix this bug?**
No

**Comment by josegutierro** [comment]
no one?

**Comment by feross** [comment]
This was an issue in `standard`, not the VSCode extension. It was fixed in `standard` 15.
