### ISSUE TITLE
Fetch API not defined

### ISSUE THREAD

**Issue by lndgalante** [standard/vscode-standard#11]
I'm wondering  why I always have this linting warning if fetch lives in the browser?

<img width="611" alt="screenshot" src="https://cloud.githubusercontent.com/assets/2475912/22176927/42863d84-dff3-11e6-8094-88f0a860a6a4.png">

Thanks!

**Comment by chenxsan** [comment]
`window` is the only allowed global variable when you are running standard.js.

But you can define another global variables in VSCode `settings.json` file as the code below shows:

```
	"standard.options": {
		"enable": true,
		"globals": [
			"fetch" // <= here
		]
	},
```
