### ISSUE TITLE
standard.ignoreDirectories will be better

### ISSUE THREAD

**Issue by andyyxw** [standard/vscode-standard#119]
**What version of this package are you using?**
`standard 14.3.4`
**What problem do you want to solve?**
I want to disable globally `standard` in some projects, like Enterprise Project whitch has own eslint rules.
**What do you think is the correct solution to this problem?**
Can't enabled in a project and disabled in another project at the same time.
**Are you willing to submit a pull request to implement this change?**

**Comment by theoludwig** [comment]
You can disable the extension globally in vscode with : `"standard.enable": false` in settings.json.
Then you can enable the extension in one specific project with the same settings in the root of your project : `.vscode/settings.json`.
