### ISSUE TITLE
package.json settings are ignored

### ISSUE THREAD

**Issue by Jakobud** [standard/vscode-standard#12]
According to the StandardJS project, you should be able to add standard options to your project's package.json file. For example, when I'm using Mocha for some Unit Testing, I need to define some globals:

```
...
"standard": {
  "globals": [
    "describe",
    "it"
  ]
}
...
```

But this extension appears to ignore the package.json file. The bad side is that this forces you to put all options for all projects into your "standard.options" configuration setting. Can you please make this so that it looks for the `package.json` and uses the options set accordingly? It should look in the current directory of the file it's linting for a `package.json` and if it doesn't find it, then to go up a directory and look there, repeat, repeat until it finds one.

**Comment by chenxsan** [comment]
@Jakobud Hi, sorry for this late response.

I tested it on VSCode 1.12.1 with vscode-standard-js 1.1.0 from marketplace, actually it does work as expected:

<img width="1277" alt="screen shot 2017-05-06 at 11 03 50 am" src="https://cloud.githubusercontent.com/assets/1091472/25769421/da83b170-324b-11e7-88f6-817c88efb5e1.png">

The problem here is when you add items to `globals` list in package.json at runtime, the extension won't read them dynamically, you have to disable the extension for workspace first and enable it then.

**Comment by Jakobud** [comment]
Ah that makes sense now. Does it also work if you restart VSCode?

**Comment by akwanashie** [comment]
This does not seem to work if the package.json file is in a sub-folder. Any recommendations?

**Comment by chenxsan** [comment]
@akwanashie It won't work. Also I don't think it make sense to resolve `package.json` in any sub-folders since you have to loop them to find it?

**Comment by akwanashie** [comment]
Probably right @chenxsan

**Comment by Jakobud** [comment]
It would not make sense for something to look in a subfolder for `package.json`. It makes sense for it to recursively look up a directory, until it finds one, because it's guaranteed that will only ever find a single `package.json` before it stops.

But going down into subdirectories, the opposite direction doesn't make sense. What happens if you have 5 subdirectories, each with a different `package.json`? What would be the expected result there?

**Comment by jack-lewin** [comment]
I've just found this bug too. Surely it should search up directories, from the location of the current file? This would mirror npm's behaviour:

```
/project
  /subfolder
    index.js
    package.json

  /another-subfolder
    app.js
    package.json
```

I would expect that `index.js` and `app.js` would both take settings from their respective `package.json` files - currently, I think the extension only looks in the root directory of the workspace.

**Comment by chenxsan** [comment]
@jack-lewin If you open `project` folder as a workspace in vscode, then the answer is yes, this extension will only search the root directory for `package.json`. But I think you can make use of [multi root workspace](https://github.com/Microsoft/vscode/issues/28344), though I haven't test it yet.

**Comment by jack-lewin** [comment]
@chenxsan awesome, thanks for the link! I did some more digging and it looks like it's a wider problem with VS Code.

If anyone else is having problems with using this extension within a monorepo, the following steps worked for me:

1. Install the VS Code Insiders build from https://code.visualstudio.com/insiders/
2. Go to File -> Add folder to workspace...
3. Add each repo/sub-folder to your workspace
4. The extension looks for `package.json` in the root of each folder that you added to the workspace.
5. Add your config per-project, as per the first post in this issue.

See the [June 2017 release notes](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_14.md#preview-multi-root-workspaces) for more detail! Hopefully this will be in the stable release soon 🙏

**Comment by mcdado** [comment]
Just had the same issue, basically my root (let's say _my-project_) has a subdirectory (themes/_theme-name_) which has the package.json file. All the JS files files are in this directory anyway. If i run standard/semistandard from the command line while inside this theme directory, it picks up the package config, while if I run it from the root it doesn't... is it possible to resolve the package.json relative to the file and not to the project directory?
