### ISSUE TITLE
Publish new version to marketplace

### ISSUE THREAD

**Issue by tume** [standard/vscode-standard#121]
Would be nice have ts-standard support working out of the box.

**Comment by theoludwig** [comment]
Yes, pull request merged since Aug 04 and nothing since then.
Can someone of the organization can publish this new version please ?

**Comment by feross** [comment]
I am happy to publish a new version, but there is currently a compile error on `master`. If someone familiar with TypeScript could please fix this up, then I'm happy to publish.

Here's what I get when I run `npm run compile`:

```

> vscode-standardjs@1.3.0 compile /Users/feross/code/vscode-standardjs
> npm run compile:client && npm run compile:server


> vscode-standardjs@1.3.0 compile:client /Users/feross/code/vscode-standardjs
> tsc -p ./client/tsconfig.json

node_modules/@types/node/index.d.ts:20:1 - error TS1084: Invalid 'reference' directive syntax.

20 /// <reference lib="es2015" />
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by tume** [comment]
I get the same error as well if I'm upgrading @types/node to latest version allowed by package.json (6.14.13).

Downgrading back to 6.0.88 seems to work fine. Not so familiar with @types/node releases so can't really comment which version should be the safe bet for TS 2.x if the problem really lies there.

**Comment by LinusU** [comment]
We should probably bump Typescript up from 2.4 which is an ancient version, PR welcome ☺️

**Comment by feross** [comment]
> Downgrading back to 6.0.88 seems to work fine

Interesting. @LinusU Do you think I should do that and publish a new version of the extension? Or should we clean things up / update TypeScript, etc. first?

**Comment by LinusU** [comment]
Updating TypeScript shouldn't affect anything external so I don't think that we should block on that. If downgrading works than go for that 🚀

**Comment by feross** [comment]
Sounds good. One other thing – I don't know how to test it before publishing – can someone who's built a VSCode extension post some instructions here to help me out?

**Comment by LinusU** [comment]
It was a while since I was working on an VS Code extension, but I _think_ that you can run `npm run package` which will create a `*.vsxi` file. You can then open that file in VS Code to install the extension.

I'm actually not using this extension anymore (I'm using the eslint one), so I'm not super up to date with everything

**Comment by feross** [comment]
Alright – I just updated the extension! Version 1.4.0 should be released now!

![giphy](https://user-images.githubusercontent.com/121766/54960514-2af5b300-4f1a-11e9-8dc0-3a5378ed0aac.gif)

**Comment by feross** [comment]
We're looking for a new maintainer or two to help with this repo. This extension has 300k+ users on VSCode – your work will have a huge impact!

Good first issues:

- Update TypeScript to the latest version https://github.com/standard/vscode-standardjs/issues/130
- Test out this PR and confirm it works: https://github.com/standard/vscode-standardjs/pull/126
- Go through the open issues and send PRs for any that look easy to fix
- Go through the open issues and comment "This issue should be closed" for the issues that are invalid/already fixed/duplicate, etc.
