### ISSUE TITLE
Problems during setup with ts-standard

### ISSUE THREAD

**Issue by magicaltoast** [standard/vscode-standard#123]
### How I can properly set up a standard extension to work with ts-standard?

**What version of this package are you using?**

1.3.0

**What operating system, Node.js, and npm version?**

OS - Ubuntu regolith, 
Node - v14.9.0
Npm - 6.14.8

**What happened?**

Cannot select ts-standard as standard.engine

**What did you expect to happen?**

Nothing special, I have installed ts-standard globally and as a dev dependency of my project.
I went to the settings tab in an extension and the only available options are:
- standard
- semistandard
- standardx

Even when I edit the JSON file containing my settings, nothing happened. 
Also ( When I was editing it vsc gave me an error that i cannot set this setting to ts-standard)

**Are you willing to submit a pull request to fix this bug?**

Sorry, but I don't know how to fix it :(

**Comment by theoludwig** [comment]
Yep, it is already implemented thanks to this pull request #103 but not yet published to VSCode marketplace, as a workaround you can clone this repo on master branch and follow the instructions to package the extension, so you can install it yourself.

Hopefully, they will publish the new version of the extension soon...
It seems like this project is abandoned sometime.
See #121 issue.

**Comment by feross** [comment]
Please see: https://github.com/standard/vscode-standardjs/issues/121 I need help getting the code on `master` to build successfully so I can publish a new version. PRs welcome!
