### ISSUE TITLE
Issue with typescript config

### ISSUE THREAD

**Issue by iiskaandar** [standard/vscode-standard#125]
**What version of this package are you using?**
1.3.0

**What operating system, Node.js, and npm version?**
Macos, node - 12.4.0, npm- 6.9.0

**What happened?**
I've set in settings.json that config:
```
  "standard.validate": [
    "typescript",
    "typescriptreact"
  ],
  "javascript.validate.enable": false,
  "standard.autoFixOnSave": true
```

I've installed standards and parsers for typescript. I wanted to use standard.js with React and Typescript. But when I install this plugin, it shows me an error with 'interface' and 'type'.

<img width="455" alt="Screenshot 2020-09-24 at 11 27 45" src="https://user-images.githubusercontent.com/31919437/94127261-01904d00-fe59-11ea-9352-7ca85a3bc492.png">
<img width="483" alt="Screenshot 2020-09-24 at 11 27 20" src="https://user-images.githubusercontent.com/31919437/94127269-035a1080-fe59-11ea-83a4-efa8fad0acd7.png">

**What did you expect to happen?**
I expected to not show this error.

**Comment by theoludwig** [comment]
@iiskaandar If you're using TypeScript, I recommand you to use `ts-standard` instead of the `standard` javascript.

**Comment by theoludwig** [comment]
This issue should be closed.
