### ISSUE TITLE
Parsing error: No Babel config file detected

### ISSUE THREAD

**Issue by marcinczenko** [standard/vscode-standard#134]
**What version of this package are you using?**
`v1.4.0`

**What operating system, Node.js, and npm version?**
`macOS Catalina v10.15.7`, `node v14.15.0`, `nom v6.14.8`, `yarn 1.19.0`.

**What happened?**
Getting `Parsing error: No Babel config file detected` in VSCode while running standard from command-line works ok.

As recommended in https://github.com/eslint/eslint/issues/13542#issuecomment-667437352 it is now recommended to use `@babel/eslint-parser` instead of `babel-eslint` in order to get fixes to things like `TypeError: Cannot read property 'value' of null `. My standardjs configuration is in `package.json`:

```json
"standard": {
    "parser": "@babel/eslint-parser",
    "ignore": [
      "**/node_modules/**",
      "**/public/**",
      ....
    ],
    "envs": [
      "es6",
      "browser",
      "jest"
    ]
  }
```

and I have this in my VSCode settings:

```json
"javascript.validate.enable": false,
"standard.usePackageJson": true,
"standard.autoFixOnSave": true,
```

Unfortunately with this config I am getting `Parsing error: No Babel config file detected` in each single file that I am open in the editor.

**What did you expect to happen?**
Expect linting to work in VSCode.

**Are you willing to submit a pull request to fix this bug?**
No

**Comment by feross** [comment]
What version of `standard` are you using?

```bash
standard -v
npx standard -v
```

**Comment by marcinczenko** [comment]
```bash
$ yarn standard --version
16.0.2
```

**Comment by theoludwig** [comment]
Closing as it is a duplicate of #100.
And there is actually a solution, reopen if you think it's a mistake, thanks!
