### ISSUE TITLE
Seeking testers! Confirm that the version on `master` works so we can publish a new version

### ISSUE THREAD

**Issue by feross** [standard/vscode-standard#135]
Thanks to @Divlo's efforts in https://github.com/standard/vscode-standardjs/pull/132, this extension has been massively updated for the latest version of TypeScript and it now passes the `ts-standard` linter.

Since the changes were quite large, before we put out a new release, **I'd like at least 5 VSCode users to run the code on `master` and report no problems.**

If you'd like to test it out and confirm it works for your use case, then please follow these steps:

1. Run `npm install`
2. Run `npm run package` to build a .vsix file
3. You can install it with `code --install-extension vscode-standardjs.vsix`

If everything works for you, post a comment here indicating it worked for you.

**Comment by elvis-pereira** [comment]
I just tested, it's working

**Comment by lucas-santoni** [comment]
I tested `master` and noticed this: https://github.com/standard/vscode-standardjs/pull/126#issuecomment-731852303.

**Comment by yelwinsoe** [comment]
I've just tested, it's working fine.

**Comment by toddbluhm** [comment]
I have been using the `master` branch version since #132 landed and everything has been working great so far...though my testing has been limited to `ts-standard` usage.

**Comment by jamesorlakin** [comment]
I can confirm `master` (on `0f92bb6`) works with ts-standard and the new errorsAsWarnings setting.

![image](https://user-images.githubusercontent.com/7294642/100548039-efb89500-3261-11eb-8c3a-f70581fcb837.png)

However, I can't seem to get normal `standard` working in the same project. I've uninstalled `ts-standard` and plopped in `standard` instead, but then get a strange globbing error to do with the ignore library.
![image](https://user-images.githubusercontent.com/7294642/100548265-5db18c00-3263-11eb-9ba7-b83cce4bdaa8.png)

This project is not in a Git registry (no .gitignore) nor have I set anything ignore-ey that I'm aware of 🙂

**Comment by theoludwig** [comment]
Right @jamesorlakin!
There are always bugs ah ah... 😅

The issue was because of #140. I cancel the changes of the PR (locally) and it seems to work as expected everywhere, but of course we can't have multiple project as it was the purpose of the PR. 
We will need to investigate further #140 before releasing `v1.5.0`.

Basically we remove `&& settings.engine !== 'standard'` of this line https://github.com/standard/vscode-standardjs/blob/0f92bb6687eed39734d459c8a65594c67fd3d8aa/server/src/server.ts#L892

And it's working but it doesn't solve #140.

**Comment by lucas-santoni** [comment]
@Divlo I can confirm that https://github.com/standard/vscode-standardjs/pull/126#issuecomment-731852303 is fixed for me on `master`. Thank you!
