### ISSUE TITLE
Support projects not using the standard

### ISSUE THREAD

**Issue by miljan-aleksic** [standard/vscode-standard#14]
Hi! I have many projects not using this standard, but the plugin insist with:

```
Failed to load the standard library.
To use standard in this workspace please install standard using 'npm install standard' or globally using 'npm install -g standard'.
You need to reopen the workspace after installing standard.
```

How can I disable that?

**Comment by chenxsan** [comment]
You can run command `Disable JavaScript Standard Style for this Workspace` in the latest 1.0.9 version, it will create a new file `.vscode/setttings.json` under your project root folder with `standard` disabled:

```json
{
  "standard.enable": false
}
```
Let me know if it works for you.

**Comment by miljan-aleksic** [comment]
I would expect to be the other way around, being standard disabled by default, but the settings works. Thanks.
