### ISSUE TITLE
Not working with eslint-plugin-html

### ISSUE THREAD

**Issue by johannes-z** [standard/vscode-standard#17]
I have a `vue` file, and applying `fix` doesn't do anything. I installed the `eslint-plugin-html` as per the docs, but after the configuration, the extension doesn't even work on normal `js` files anymore. 

JavaScript Standard Style is on version `1.1.0`, `eslint-plugin-html` is on version `2.0.1`.

These are all the standard related options in my `settings.json`:

```json
    "standard.autoFixOnSave": true,
    "standard.validate": [
      "javascript",
      "javascriptreact",
      "html"
    ],
    "standard.options": {
        "plugins": ["html"]
    }
```

The only output I get from `standard` is:

```
[Info  - 18:24:04] JavaScript Standard Style server is running.
[Info  - 18:24:05] standard library loaded from: <User_Path>\node_modules\standard\index.js
```

**Comment by chenxsan** [comment]
1. Did it work on `js` files before the configuration?
2. Did you set the language mode of `vue` files to `html`?

**Comment by johannes-z** [comment]
1. Yes. It stopped working after adding the `options` to my settings. 
2. No, I was using a vue plug in, so the language was set to `Vue Component`. I will try to set it to HTML asap. 

edit: 2) Actually, it was set to `HTML`. I just double-checked.

**Comment by johannes-z** [comment]
Also, I tried installing `eslint-plugin-html` and `standard` both locally and globally, but that didn't work either.

**Comment by johannes-z** [comment]
I deleted all globally installed packages, and reinstalled `standard` and `eslint-plugin-html`, now it's working. I guess my installation of `standard` was just outdated...
