### ISSUE TITLE
JavaScript Standard Style and React Native: Unexpected token =

### ISSUE THREAD

**Issue by DFelten** [standard/vscode-standard#18]
I'm not sure if this should work with React Native, but at the moment there is a problem with React Native and React Navigation. A correct code is displayed as incorrect.

It is about [this](https://reactnavigation.org/docs/intro/) working example:
```
class ChatScreen extends React.Component {
  static navigationOptions = {
    title: 'Chat with Lucy',
  };
  render() {
    return (
      <View>
        <Text>Chat with Lucy</Text>
      </View>
    );
  }
}
```
![image](https://cloud.githubusercontent.com/assets/1169185/23590612/83bf5922-01e3-11e7-91ed-ea1a058689ef.png)

Is the code incorrect? Or is it not compatible with React Native?

**Comment by chenxsan** [comment]
You need to customize standard parser to https://github.com/babel/babel-eslint:

```json
"standard.options": {
		"enable": true,
		"parser": "babel-eslint"
	},
```
Remember to install babel-eslint either locally under you project or globally.

<img width="403" alt="screen shot 2017-03-06 at 8 03 14 am" src="https://cloud.githubusercontent.com/assets/1091472/23592958/67cb32da-0243-11e7-90b6-de55b800e8bf.png">

**Comment by DFelten** [comment]
Perfect, thanks for the quick and good help!
