### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by sean-hill** [standard/vscode-standard#2]
Hey there, I have installed the plugin, installed `standard`, and rebooted the Workplace, but I still get the error:

    To use standard in this workspace please install standard using 'npm install standard' or globally using 'npm install -g standard'.
    You need to reopen the workspace after installing standard.

I can't seem to get it to work 😦

**Comment by chenxsan** [comment]
Which version of `standard` do you have?

**Comment by sean-hill** [comment]
I currently have version 8.6.0 installed on my machine.



-- 
Sean Hill
me@seanhill.info
www.seanhill.info

On November 23, 2016 at 6:09:04 PM, 陈三 (notifications@github.com) wrote:

Which version of standard do you have?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/chenxsan/vscode-standardjs/issues/2#issuecomment-262666962>,
or mute the thread

**Comment by chenxsan** [comment]
I'm running 8.6.0 with VSCode 1.7.2 on macOS.

Seems VSCode could not resolve `standard` package when [initializing](https://github.com/chenxsan/vscode-standardjs/blob/master/eslint-server/src/server.ts#L182). I'll check it to see if anything I can fix.
