### ISSUE TITLE
Fixing all auto-fixable problems doesn't work all the time

### ISSUE THREAD

**Issue by denizdogan** [standard/vscode-standard#20]
-  StandardJS version? 9.0.1
- VSCode version? 1.10.2

To auto-fix the formatting, I need to run "Fix all auto-fixable problems" several times.

[Here is a video of the problem](https://streamable.com/4quuf)

**Comment by chenxsan** [comment]
It's a bug in vscode-eslint https://github.com/Microsoft/vscode-eslint/issues/154.

**Comment by denizdogan** [comment]
No longer relevant to me, closing
