### ISSUE TITLE
After adding  @babel/eslint-parser, imports show "No Babel config file detected" in vsCode

### ISSUE THREAD

**Issue by jpbnetley** [standard/vscode-standard#209]
**What version of this package are you using?**
v1.4.0

**What operating system, Node.js, and npm version?**
macOS Big Sur v11.3.1
Node v16.1.0
npm v7.11.2

**What happened?**
I added the [@babel/eslint-parser](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint) to the package json,
But vscode now states that all imports require a babel config
```
No Babel config file detected
```

**What did you expect to happen?**
The import to resolve normally since the tests standard js does not give an error when running it via the terminal.

**Are you willing to submit a pull request to fix this bug?**
Yea I can give it a go.
This issue was discussed here: https://github.com/standard/vscode-standard/issues/100#issuecomment-842690791

Where the pr made [here](https://github.com/standard/vscode-standard/pull/207/files) fixed it.

I can try and use what they did in that pr.

Let me know what is best.

**Comment by jpbnetley** [comment]
I saw that
<img width="1052" alt="sam" src="https://user-images.githubusercontent.com/25173863/118622795-eeefcd00-b7c7-11eb-8c65-246243af8a9f.png">
and
<img width="1056" alt="standard" src="https://user-images.githubusercontent.com/25173863/118622842-f8793500-b7c7-11eb-8839-d58a19def647.png">

Links to the same repo, but only the one by the author 'Standard' gets the update.

**Comment by feross** [comment]
You need to use the new version of the extension. We moved it to a new package name `standard.vscode-standard` which you can download here: https://marketplace.visualstudio.com/items?itemName=standard.vscode-standard

We'll be marking the other version `chenxsan.vscode-standardjs` as deprecated soon.
