### ISSUE TITLE
Feature Request: Check for local standard installation.

### ISSUE THREAD

**Issue by DylanPiercey** [standard/vscode-standard#21]
I've just recently switched from atom and have stumbled upon this package. It is working exactly as I expect however there is one feature I would love to have from https://atom.io/packages/linter-js-standard.

Basically it will check your package.json for to see if you have standard installed and use it if it is there, and it has an option to disable standard linting if is missing. This makes it easy when switching to a standard project since you no longer have to manually enable or disable the plugin.

This could also tie into: https://github.com/chenxsan/vscode-standardjs/issues/16

Thanks so much for your work on this plugin - I understand that I am requesting you use your free time to build in this feature.

**Comment by bojand** [comment]
I think [this change](https://github.com/chenxsan/vscode-standardjs/commit/be3cd3e95fab5b790e5f71ae2142a13dff2f8ff2) made this issue somewhat more annoying... For most of my personal projects I use standardjs, and at work we use semistandard, and I don't install either globally for various reasons, one being that I use multiple versions of node.js as well. So I usually have to rely on package.json for dependancies almost exclusively. Now with this change in any of my semistandard projects it pops up with an error message. I'll try and debug this some more and hopefully figure some code and do up a PR. Any guidance or pointing me in the right direction would be helpful. thanks.

**Comment by chenxsan** [comment]
@bojand Ok, I'm going to revert it until this feature is added. You might want to check why I added that change [here](https://github.com/chenxsan/vscode-standardjs/issues/27).

**Comment by bojand** [comment]
Hello, thanks! Yes I saw that issue. An optional workaround might be to have a setting to suppress the alert? At least until this feature is implemented? Just an idea.

**Comment by chenxsan** [comment]
@bojand I'll keep the issue opened until this one is fixed.

**Comment by chenxsan** [comment]
@DylanPiercey @bojand @BernhardRode

We finally bring this feature into 1.2.0! Thanks to @bojand!

Anyway, I just published a vsix file [here](https://github.com/chenxsan/vscode-standardjs/releases/tag/v1.2.0), it's not published to marketplace yet, so you could install it with `code --install-extension xxx.vsix`, would love to see if it meets your need.

**Comment by BernhardRode** [comment]
Awesome! Thank you so much @bojand & @chenxsan!

**Comment by LitoMore** [comment]
@chenxsan How about change the `feature request` label color to blue or green? It just looks like a `bug request`. 😅

**Comment by chenxsan** [comment]
👍 @LitoMore make sense.

**Comment by BernhardRode** [comment]
Tried 1.2.0 for some time now. Works like a charm. Ready to release =)

**Comment by chenxsan** [comment]
Just published 1.2.0 to marketplace, if anyone got a new problem please file a new issue. I'll close this one.
