### ISSUE TITLE
Can not load global module 'eslint-plugin-html'.

### ISSUE THREAD

**Issue by blade254353074** [standard/vscode-standard#25]
- StandardJS version?
10.0.2
- VSCode version?
1.12.1
- StandardJS configuration?
```JSON
"standard.enable": true,
"standard.validate": [
  "javascript",
  "javascriptreact",
  "vue",
  "html"
],
"standard.options": {
  "plugins": ["html"],
  "parser": "babel-eslint",
  "ignore": [
    "node_modules/**"
  ],
  "globals": ["$", "React", "Vue"],
  "parserOptions": {
    "ecmaVersion": 7,
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": true
    }
  },
  "env": {
    "commonjs": true,
    "node": true,
    "browser": true
  }
}
```

# Problem:

VScode pop the following error continuously, when I'm editing JS files.

![image](https://cloud.githubusercontent.com/assets/9346008/25981618/e243eea4-3708-11e7-88c1-286fd6896394.png)

> `Failed to load plugin html: Cannot find module 'eslint-plugin-html'`

**Unless installed `eslint-plugin-html` module at local project.**

# Additional information

![image](https://cloud.githubusercontent.com/assets/9346008/25981809/111a1856-370a-11e7-8197-8ed6a2cbbf37.png)

**Comment by chenxsan** [comment]
Looks like you have `standard` installed locally under your project, then you should have those plugins installed locally too. Or it will fail to resolve.

**Comment by blade254353074** [comment]
Can we fallback to global module, when local node_modules doesn't have it?

**Comment by chenxsan** [comment]
I'm not sure if it will work, you can check the standardjs doc https://github.com/feross/standard#how-do-i-use-experimental-javascript-es-next-features:

> If standard is installed globally (i.e. npm install standard --global), then be sure to install babel-eslint globally as well, with npm install babel-eslint --global.

Maybe you could raise an issue there :)

**Comment by blade254353074** [comment]
Oh...it's not working. 😞
