### ISSUE TITLE
Better options default to reduce configurations overhead

### ISSUE THREAD

**Issue by theoludwig** [standard/vscode-standard#261]
**What version of this package are you using?**

v1.5.1

**What problem do you want to solve?**

Currently, the defaults options (`.vscode/settings.json`) for this extension are not correct in terms of "best practices" as it encourages global installation, global configuration (currently it is enabled by default but instead it should be enabled per project) and recommends to disable the built-in VSCode validator (`"javascript.validate.enable": false`) for no reason.

These defaults contradict, one of the `standard` goals to make it work out of the box.

**What do you think is the correct solution to this problem?**

- We need to change the default options:

  - `"standard.enable": false`
  - `"standard.usePackageJson": true`

- Instead of recommending (in the README)

> 3. Disable the built-in VSCode validator

We can provide an example of `.vscode/settings.json` for the third steps of "How to use".

After these improvements, we can have a working VSCode setup with `standard` with only one line of config in `.vscode/settings.json` :

```json
{
  "standard.enable": true
}
```

This is necessary to enable the extension only for the project we are currently working on, that way we don't need to disable this extension if we are working on a project that doesn't use `standard`.

**Note:** This is a **BREAKING CHANGE**.

**Are you willing to submit a pull request to implement this change?**

Yes!

**Comment by hutch120** [comment]
@Divlo Completely agree. Perhaps some examples for popular libraries like CRA that seems to also need the workingDirectories directive. 

The following example seems to work for a CRA starter example (assuming an app name of  /app) and doesn't stop formatting of other files.

```
{
  "editor.formatOnSave": true,
  "[javascript]": {
    "editor.formatOnSave": false
  },
  "[javascriptreact]": {
    "editor.formatOnSave": false
  },
  "[typescript]": {
    "editor.formatOnSave": false
  },
  "[typescriptreact]": {
    "editor.formatOnSave": false,
  },
  "standard.enable": true,
  "standard.engine": "ts-standard",
  "standard.usePackageJson": true,
  "standard.treatErrorsAsWarnings": true,
  "standard.autoFixOnSave": true,
  "standard.workingDirectories": [
    "./app"
  ]
}
```
