### ISSUE TITLE
Detect typescript for ts-standard

### ISSUE THREAD

**Issue by davidystephenson** [standard/vscode-standard#267]
**What version of this package are you using?**
1.4.1

**What problem do you want to solve?** 
Every time I move from a JavaScript to a TypeScript project, I must manually change the standard engine to `ts-standard` in the VS Code settings panel. Setting a `standard.engine` in the project's `package.json` has no effect.

**What do you think is the correct solution to this problem?**
Preferably `vscode-standard` would support detecting TypeScript files and automatically switching to `ts-standard`. Alternatively reading the engine from the `package.json` would be an improvement.

**Are you willing to submit a pull request to implement this change?**
I am unable.

**Comment by theoludwig** [comment]
Hey! @davidystephenson :wave:
Thanks for your report!

If you set `"standard.usePackageJson": true` in `.vscode/settings.json` or in the VSCode settings panel, it will automatically detect the engine you're using by checking in your `devDependencies` in the `package.json` of your project.

> Setting a `standard.engine` in the project's `package.json` has no effect.

Yes, that's normal, `standard.engine` is specific to the settings to this VSCode extension. :smile:

> What version of this package are you using?
1.4.1

Please update the extension to `1.5.1`. :+1:

**Comment by davidystephenson** [comment]
Thanks, works great.
