### ISSUE TITLE
Error: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by hmdhk** [standard/vscode-standard#28]
- StandardJS version: 1.1.4
- VSCode version: May 2017 (version 1.13)

Opening any file in vs code show this error. Disabling the extension resolves the issue.

**Comment by onimushapooh** [comment]
i have the same problem. please fix this asap

**Comment by chenxsan** [comment]
@jahtalab @onimushapooh The latest StandardJS version is [10.0.2](https://standardjs.com/changelog.html).

**Comment by hmdhk** [comment]
@chenxsan , Sorry I meant vscode-standardjs version 1.1.4 not StandardJS version

**Comment by onimushapooh** [comment]
<img width="1016" alt="screen shot 2560-06-19 at 11 36 22" src="https://user-images.githubusercontent.com/703309/27269774-b63ca136-54e3-11e7-8553-069d1b5a5a6c.png">

i got this error. is there a way to fix this?

Thank you.

**Comment by chenxsan** [comment]
@onimushapooh Please give me more details:

1. VSCode version
2. VSCode-standardjs version
3. StandardJS version
4. StandardJS config
5. Any plugins?

**Comment by chenxsan** [comment]
@jahtalab @onimushapooh 

Hi guys, I'm running VSCode 1.13.1 on macOS with StandardJS 10.0.2 and the latest vscode-stanardjs i.e 1.1.4, and here's my config in vscode `settings.json` file:

```
	"standard.validate": [
		"javascript",
		"javascriptreact",
		{ "language": "html", "autoFix": true }
	],
	"standard.options": {
		"enable": true,
		"plugins": ["html"],
		"parser": "babel-eslint"
	},
	"standard.semistandard": false,
	"javascript.validate.enable": false,
```
Since it's working fine on my computer, so I would need more info to debug this.

**Comment by onimushapooh** [comment]
Hi,

Thank you for quick reply,

   1. VSCode version <= 1.13.1 (Latest Mac version)
   2. VSCode-standardjs version <= 1.14
   3. StandardJS version <= 10.0.2
   4. StandardJS config <= default config
   5. Any plugins? <= No plugin

Thank you,

**Comment by onimushapooh** [comment]
Hi, 

Thank you for quick reply,
VSCode version <= 1.13.1 (Latest Mac version)
VSCode-standardjs version <= 1.14
StandardJS version <= 10.0.2
StandardJS config <= default config
Any plugins? <= No plugin


i just copy your config. but still not works

<img width="422" alt="screen shot 2560-06-20 at 19 27 58" src="https://user-images.githubusercontent.com/703309/27333032-9d02b438-55ee-11e7-9712-20f2fdab33a7.png">

Thank you.

**Comment by chenxsan** [comment]
@jahtalab @onimushapooh I'm sorry guys, I really want to help, but can't reproduce it on my computer.

**Comment by feross** [comment]
This is a very old issue and is likely resolved.
