### ISSUE TITLE
how do I assign a shortcut to format

### ISSUE THREAD

**Issue by marcosfede** [standard/vscode-standard#3]
Is it possible to assign a keyboard shortcut to format using standard, or to adapt the default code formater so it uses this package to format javascript?

**Comment by chenxsan** [comment]
We have a [`standard.executeAutofix`](https://github.com/chenxsan/vscode-standardjs/blob/master/eslint/package.json#L84) command, and you could define a keyboard shortcut in your `keybindings.json` file:

```
[
  {"key": "alt+cmd+f", "command": "standard.executeAutofix"}
]
```
I'm afraid the default code formatter won't work.

**Comment by marcosfede** [comment]
Excellent, thank you!

**Comment by sapolio** [comment]
Finding this solution is not a piece of cake. ;)
