### ISSUE TITLE
After installation:  Cannot find module 'babel-eslint'

### ISSUE THREAD

**Issue by BurtHarris** [standard/vscode-standard#31]
After installing vscode-standardjs, VS code keeps displaying a message saying:

> Cannot find module 'babel-eslint'

- StandardJS version? 10.0.2
- VSCode version? 1.13.1 - 379d2efb5539b09112c793d3d9a413017d736f89
- StandardJS configuration?

- Visual Studio Extensions
JavaScript Standard Style: 1.1.6
JavaScript Standard Format: not installed, but 0.0.12 listed.

Have I got the right version installed?

**Comment by chenxsan** [comment]
Are you copying standard config from the marketplace?

>   "standard.options": {
      "globals": ["$", "jQuery", "fetch"],
      "ignore": [
          "node_modules/**"
      ],
      "plugins": ["html"],
      "parser": "babel-eslint"
  }

Make sure you really need `babel-eslint`, if you have no idea what is it, just remove it from `standard.options`. You have to install it if it's presented in `standard.options`.

**Comment by BurtHarris** [comment]
Hmm, no I didn't copy anything from the marketplace.   I installed it from the VSCode "EXTENSIONS" panel.

For one project (where I was seeing the message) I have the following settings enabled:
```
// Place your settings in this file to overwrite default and user settings.
{
    "javascript.validate.enable": false,
    "standard.enable": true
}
```

I don't really think I need babel-eslint, there's no Babel in most of what I do, which is why this message was so surprising.    I don't seem to have `standard.options` in either my project or user settings files.

**Comment by BurtHarris** [comment]
P.S.  Mostly I write in TypeScript, but the project I enabled this for was pure JavaScript.

**Comment by chenxsan** [comment]
Can you share the `package.json` file under your project?

**Comment by BurtHarris** [comment]
The whole project is available here: https://github.com/BurtHarris/gulp-first

**Comment by BurtHarris** [comment]
Repro steps: 
1. Open `code` in project above.
2. In EXTENSIONS window, Install and/or enable **JavaScript Standard Style** 1.1.6
3. Open file `index.js`

Observed: Message saying "ERROR Cannot find module babel-eslint"

**Comment by chenxsan** [comment]
<img width="674" alt="screen shot 2017-07-04 at 11 06 59 am" src="https://user-images.githubusercontent.com/1091472/27813485-ddcfe2dc-60a8-11e7-971f-b1c4639d08e7.png">

Works fine on my computer. Could you paste your `settings.json` file of VSCode?

This is what I have:

<img width="925" alt="screen shot 2017-07-04 at 11 08 59 am" src="https://user-images.githubusercontent.com/1091472/27813550-3e0b10a4-60a9-11e7-9d26-73ebb8757440.png">

**Comment by BurtHarris** [comment]
My user settings:
```
// Place your settings in this file to overwrite the default settings
{
    "search.exclude": {
    },
    "tslint.enable": true,
    "git.confirmSync": false,
    "workbench.colorTheme": "Visual Studio Dark",
    "window.zoomLevel": 1,
    "typescript.check.tscVersion": false,
    "files.autoSave": "afterDelay",
     "window.title": "${dirty}${activeEditorLong}${separator}${rootName}${separator}${appName}",
    "cSpell.userWords": [
        "appveyor",
        "Gitter",
        "AppVeyor"
    ]
}
```
![err](https://user-images.githubusercontent.com/2715647/27813668-5913168a-602c-11e7-9890-cc97a002d8f4.png)

**Comment by BurtHarris** [comment]
Hmm, I uninstalled a few other add-ins and the problem seems to have gone away.   I had ESLINT and TSLINT installed.

**Comment by chenxsan** [comment]
Yeah, I can see it from the status bar, ESlint is in red, it could be a problem of VSCode-eslint.

**Comment by BurtHarris** [comment]
I can confirm, it seems to be a conflict with ESLint 1.2.11 add-in.

That's no problem for me, I'll leave it uninstalled.

**Comment by chenxsan** [comment]
Glad you solve it :)

**Comment by EskelCz** [comment]
I see the same issue and I have only StandardJS enabled, no other plugin

**Comment by EskelCz** [comment]
this fixed it
https://github.com/standard/standard/issues/85#issuecomment-86132058
