### ISSUE TITLE
Change extension icon to JavaScript Standard Style Sticker

### ISSUE THREAD

**Issue by LitoMore** [standard/vscode-standard#32]
How about change the extension icon to [JavaScript Standard Style Sticker](https://cdn.rawgit.com/feross/standard/master/sticker.svg) ?

Current badge (<img width="80" src="https://cdn.rawgit.com/feross/standard/master/badge.svg" />) icon is black-text-on-dark-gray-background.

![](http://photo2.fanfou.com/v1/mss_3d027b52ec5a4d589e68050845611e68/ff/n0/0e/7n/re_460759.jpg)

The sticker (<img width="30" src="https://cdn.rawgit.com/feross/standard/master/sticker.svg" />) icon can be used to increase the readability.

## Badge (current)

<img src="https://cdn.rawgit.com/feross/standard/master/badge.svg" />

## Sticker (recommend)

<img width="150" src="https://cdn.rawgit.com/feross/standard/master/sticker.svg" />

```
https://cdn.rawgit.com/feross/standard/master/sticker.svg
```

**Comment by chenxsan** [comment]
Yeah, I think it's a good idea, pull request is welcomed.
