### ISSUE TITLE
Enhancement: possibility to run for all files in workingDirectories on save

### ISSUE THREAD

**Issue by pdesjardins90** [standard/vscode-standard#34]
It would be very helpful to be able to run on all files listed in workingDirectories upon save, not just the current file! I could quickly work through the error panel to assess all problems.

**Comment by chenxsan** [comment]
We can't do it since vscode-standardjs use [`lintText`](https://github.com/chenxsan/vscode-standardjs/blob/master/eslint-server/src/server.ts#L690). Also things become complex when there are many unsaved files opened in vscode.

**Comment by pdesjardins90** [comment]
Alright, I'll close this then, but if anyone ever have an idea of how to implement this feel free to reopen!
