### ISSUE TITLE
Format on save not working on .vue files

### ISSUE THREAD

**Issue by packetstracer** [standard/vscode-standard#35]
- StandardJS version?
1.1.7
- VSCode version?
1.14
- StandardJS configuration?
```
  "editor.formatOnSave": false,
  "javascript.validate.enable": false,
  "standard.validate": [
    "javascript",
    "javascriptreact",
    "html"
  ],
  "standard.options": {
    "globals": [
      "$",
      "jQuery",
      "fetch"
    ],
    "ignore": [
      "node_modules/**"
    ],
    "parser": "babel-eslint",
    "plugins": [
      "html"
    ]
  },
  "files.associations": {
    "*.vue": "html"
  },
  "standard.autoFixOnSave": true,
```

**Comment by chenxsan** [comment]
I think you need this:

```
 "standard.validate": [
     "javascript",
     "javascriptreact",
     { "language": "html", "autoFix": true }
 ],
```

**Comment by prograhammer** [comment]
Has anyone successfully got .vue files to lint (with standard) yet? I've tried the above and also all kinds of other things yet unsuccessful. I can get them to lint, but not according to standard. The .js files will lint to standard just fine.

**Comment by chenxsan** [comment]
@prograhammer What do you mean you can get them to lint but not according to standard?

**Comment by packetstracer** [comment]
@chenxsan works now for me, thanks a lot

**Comment by prograhammer** [comment]
@chenxsan if I put a semicolon after a comma or something like that it will show a red error mark. If I add extra spaces before a `}` brace then it doesn't show any error. The error will show in .js files, but not in .vue files. I've updated my settings.json like you mentioned. I can upload a repo on github for you to see as an example, but it's been working in sublime text 3.

**Comment by chenxsan** [comment]
@prograhammer An example would be helpful.

**Comment by Robula** [comment]
Similar issue, although even Format Document isn't formatting to Standard.

**Comment by eddiemonge** [comment]
I have a similar problem. I think it doesn't work in DOT-folders. If I move a file out of `.storybook` it works. Putting the file back it doesn't

**Comment by chenxsan** [comment]
@eddiemonge https://github.com/standard/standard#how-do-i-ignore-files:

> Certain paths (node_modules/, coverage/, vendor/, *.min.js, bundle.js, and files/folders that begin with . like .git/) are automatically ignored.

**Comment by eddiemonge** [comment]
`Fix all auto-fixable problems` should still work since I as the user am telling the tool to perform work on the active file. Reporting on files in ignored directores is different.

**Comment by Lynn-cc** [comment]
I found a problem that I can't use the VSCode default vue extension 'vetur' to validate the content inside `<style lang="scss">` when I set `{files.associations: "*.vue:" "html"}` option for the standard extension. I have to set `"css.validate": false` to hide the wrong css error warnings, but it may cause problem with my sass code. How could I solve this problem?

**Comment by SolT31** [comment]
My configuration works here.

standard v12.0.1
Extension v1.2.3

```
npm i -g standard
npm i -g eslint-plugin-html@4
```

settings.json
```JSON
"standard.autoFixOnSave": true,
"standard.validate": [
  "javascript",
  "javascriptreact", 
  {
    "language": "vue",
    "autoFix": true
  }
],
"standard.options": {
  "plugins": ["html"]
}
```

**Comment by mesqueeb** [comment]
+1

**Comment by tarunama** [comment]
+1

**Comment by falco467** [comment]
I'm using the same setup as @SolT31 but standard.js seems to try and parse the whole .vue file and not just the javascript in the script tag:

```
<template>
  <button @click="foo"></button>
</template>
<script>
module.exports = {
  methods: {
    async foo() { badMethod("bad quotes");;; }
  }
}
</script>
```

This example file shows only a single error by standard in line 2: `@click` - "unexpected character @".

StandardJS does not even get to the JS-lines to mark errors.

**Comment by theoludwig** [comment]
Closing as it is not related to the vscode extension but to `standard`, reopen if you think it is related to this repo. Thanks! :smile:
