### ISSUE TITLE
static propTypes = ... [standard] Parsing error: Unexpected token =

### ISSUE THREAD

**Issue by poupryc** [standard/vscode-standard#36]
![image](https://user-images.githubusercontent.com/25421857/28491856-1fe90cfe-6ef8-11e7-9734-9523900602bd.png)

Hello,
I have no, but no idea why standard shows me a mistake.
I am novice with standard, I do not know if I have offended a rules etc ...

Thank,

- StandardJS version: 1.1.7
- VSCode version: 1.14.2
- StandardJS configuration: no config

**Comment by chenxsan** [comment]
`static` is not supported by default, you need to install [`babel-eslint`](https://github.com/babel/babel-eslint), and set it as custom parser with configuration:

```
  "standard.options": {
      "parser": "babel-eslint"
  }
```

**Comment by poupryc** [comment]
Thank you for your answer, but it's really extremely weird: here is the line:
![image](https://user-images.githubusercontent.com/25421857/28493244-6cf7b444-6f13-11e7-8f2a-28a5981ce6b6.png)
The second `static` does not trigger an error 😄

**Comment by poupryc** [comment]
But the issue is resolved with `babel-eslint`

**Comment by chenxsan** [comment]
It's a serious problem, the parser just stops parsing codes after, that's why the second one does not trigger error.

**Comment by poupryc** [comment]
I think it's a bug from ESLint, but I'm not sure ... No solution to solve this problem?
