### ISSUE TITLE
Error: "glob pattern string required" on keypress

### ISSUE THREAD

**Issue by mradbourne** [standard/vscode-standard#37]
After installing the plugin, I get the error message "glob pattern string required" when editing JavaScript files. The error reappears every time a new character is typed. The plugin does not function.

- StandardJS version 10.0.2
- VSCode version 1.14.2
- StandardJS configuration: None
- Node version 6.9.1

The output tab for 'standard' in VSCode shows:

- JavaScript Standard Style server is running.
- standard library loaded from: /Users/me/.nvm/versions/node/v6.9.1/lib/node_modules/standard/index.js

The same error occurs with node 6.11.0

**Comment by chenxsan** [comment]
Are you editing untitled JavaScript file?

**Comment by mradbourne** [comment]
Ah yes. The error only occurs for unsaved files.

**Comment by ArtemGovorov** [comment]
Our user had reported the same issue: https://github.com/wallabyjs/quokka/issues/78. When a new javascript file created from our extension (without saving), vscode-standardjs [starts throwing `glob pattern string required`](https://i.gyazo.com/c366097e99e763b5a577741850152726.mp4).

If it helps, we create new untitled JavaScript files (without saving them) in our extension like this:
```javascript
workspace.openTextDocument({language: language.toLowerCase()})
        .then(openedDoc => window.showTextDocument(openedDoc)
```

If it's not easy to fix the issue, perhaps you could just disable processing of the `untitled` scheme, with a check like this:

```javascript
document.uri.scheme !== 'untitled'
```

**Comment by chenxsan** [comment]
@ArtemGovorov Thanks for the info, just push 1.1.8 to fix it.

cc @mradbourne Please update vscode-standard to the latest 1.1.8, it's fixed now.

**Comment by ArtemGovorov** [comment]
@chenxsan Awesome, thanks for the quick fix!
