### ISSUE TITLE
"Arrow Method" is not defined. (no-undef)

### ISSUE THREAD

**Issue by rochapablo** [standard/vscode-standard#38]
I'm getting the error only on vscode; When I run ```standard --fix``` no errors are shown.

```
_renderItem = ({ item }) => {
    return (...)
}
```

- StandardJS version? **10.0.2**

- VSCode version? **1.14.2**

- StandardJS configuration?

```
// Place your settings in this file to overwrite default and user settings.
{
    "javascript.validate.enable": false,
    "standard.enable": true,
    "standard.run": "onSave",
    "standard.autoFixOnSave": true,
    "standard.options": {
        "ignore": [
            "/__tests__",
            "/android",
            "/ios"
        ],
        "rules": {
            "typescript/type-annotation-spacing": "error"
        },
        "parser": "babel-eslint"
    },
    "standard.validate": [
        "javascript",
        "javascriptreact",
        {
            "autoFix": true
        }
    ]
}
```

https://github.com/standard/standard/issues/935#issuecomment-311824566

**Comment by chenxsan** [comment]
It works fine in my test, even with your standardjs configuration:

<img width="527" alt="screen shot 2017-08-03 at 8 23 53 am" src="https://user-images.githubusercontent.com/1091472/28900633-2b32cb78-7825-11e7-8e07-eb9bd956aea5.png">

Which version of `babel-eslint` do you have?

**Comment by rochapablo** [comment]
{
    "babel-eslint": "^7.2.3",
    "babel-jest": "20.0.3",
    "babel-preset-react-native": "2.0.0",
    "jest": "20.0.4",
    "react-test-renderer": "16.0.0-alpha.12",
    "standard": "^10.0.2"
}

**Comment by rochapablo** [comment]
@chenxsan, oops! I've just restart the vscode and the error was gone.
