### ISSUE TITLE
feature(settings): standard.enable : auto

### ISSUE THREAD

**Issue by BernhardRode** [standard/vscode-standard#39]
- StandardJS version?
Latest
- VSCode version?
Latest
- StandardJS configuration?
Standard =)

It would be awesome to have a option:
standard.enable : auto

It should enable all the plugins goodness, only when the current workspace has standard in its package.json.

I'm jumping between projects all the time and having standard on all the time messes things up most of the time ;)

BTW Thank you for your work!

**Comment by chenxsan** [comment]
@BernhardRode I think this request is same as https://github.com/chenxsan/vscode-standardjs/issues/21#issue-215647763 ?

**Comment by BernhardRode** [comment]
You are right. Sorry, didn't see that one.
