### ISSUE TITLE
run: onSave and autoFixOnSave is not working

### ISSUE THREAD

**Issue by Jakobud** [standard/vscode-standard#4]
I have the extension installed. My output window says:

```
[Info  - 2:57:37 PM] JavaScript Standard Style server is running.
```

And I have:

```
"standard.run": "onSave",
"standard.autoFixOnSave": true
```

But the extension does not autolint or auto fix anything when I save. I have to open my Command Palette and run `Standard JavaScript Style: Fix all auto-fixable problems` in order to auto fix anything.

What am I missing here?

**Comment by Jakobud** [comment]
Any word on why this isn't working for me?

**Comment by Jakobud** [comment]
Looks like if I have it set like this:

```
"standard.run": "onType",
"standard.autoFixOnSave": true
```

Then it works for me. It detects issues as I type them and then fixes them on save. But if you have both set to happen onSave then it can't do both at the same time.

**Comment by Kaijun** [comment]
@Jakobud you save my day
