### ISSUE TITLE
Failed to load the JavaScript Standard Style library for the document 

### ISSUE THREAD

**Issue by jcramirez** [standard/vscode-standard#42]
- OS: Windows 10
- StandardJS version: 1.1.8
- VSCode version: 1.16.0
- StandardJS configuration: "standard.semistandard": true

I keep getting this message. I haven't been able to figure out any ideas?

```
[Info  - 11:39:04 AM] JavaScript Standard Style server is running.
[Info  - 11:39:04 AM] 
Failed to load the JavaScript Standard Style library for the document 'd:\path\to\utils\config-tool\index.js'.

To use JavaScript Standard Style in this workspace please install standard using 'npm install standard' or globally using 'npm install -g standard'.
You need to reopen the workspace after installing standard.

Alternatively you can disable JavaScript Standard Style for this workspace by executing the 'Disable JavaScript Standard Style for this workspace' command.
```

**Comment by chenxsan** [comment]
Have you installed [semistandard](https://github.com/Flet/semistandard)? When you set `standard.semistandard` to `true`, I'm afraid `semistandard` should be installed instead of `standard`.

**Comment by jcramirez** [comment]
You are 100% correct. thank you very much, that completely solved my issue. Did I miss that somewhere in the documentation?

**Comment by chenxsan** [comment]
I think it's missing in the documentation. Will update it in the next version.
