### ISSUE TITLE
Running the contributed command:'format.standard' failed In vscode when fommat .vue file 

### ISSUE THREAD

**Issue by herrdu** [standard/vscode-standard#45]
- StandardJS version?
latest 

- VSCode version?
1.17.2 (1.17.2)

- StandardJS configuration?
 "javascript.validate.enable" : false,
        "beautify.config": "/Users/herrdu/.vscode/extensions/HookyQR.beautify-1.1.1/.jsbeautifyrc",
        "standard.validate": [
          "javascript",
          "javascriptreact",
          "html"
        ],
        "standard.options": {
          "plugins": ["html"]
        },
        "files.associations": {
          "*.vue": "html"
        },

- What do you have in the `OUTPUT` panel?

when use it in  .vue file , vscode will show :
"Running the contributed command:'format.standard' failed."

**Comment by chenxsan** [comment]
I don't think this extension provide a `format.standard` command. You can check all the commands here https://github.com/chenxsan/vscode-standardjs/blob/master/package.json#L158

**Comment by herrdu** [comment]
I got it .
In your readme  ,it writes  
```
Keybinding

You can also configurate keybinding in keybindings.json, for example:

[
  {"key": "shift+cmd+f", "command": "format.standard",
  "when": "editorTextFocus"}
]
```

**Comment by chenxsan** [comment]
@herrdu Are you running https://marketplace.visualstudio.com/items?itemName=chenxsan.vscode-standard-format? It's deprecated.
