### ISSUE TITLE
Built-in JavaScript formatter configurations about `space-before-function-paren`

### ISSUE THREAD

**Issue by itiut** [standard/vscode-standard#47]
- StandardJS version?
1.2.0
- VSCode version?
1.18.0
- StandardJS configuration?
default

When `editor.formatOnType` is set to `true` (default: `false`), built-in JavaScript formatter formats the typed line as it violates rule `space-before-function-paren`. This also happens when `editor.formatOnPaste` is `true`.

![format-on-type](https://user-images.githubusercontent.com/1145226/32606375-6ed92690-c598-11e7-84d5-27653823a9e0.gif)

As a workaround I override two configurations in `settings.json` as followings, and the formatter works fine.

```
  "javascript.format.insertSpaceAfterConstructor": true,
  "javascript.format.insertSpaceBeforeFunctionParenthesis": true,
```

It would be helpful if this extension overrides these configurations, or some information about this should be added to README.

**Comment by chenxsan** [comment]
@itiut Thanks for reminding! Would you love to make a pull request? I'm happy to merge it :)

**Comment by chenxsan** [comment]
Sorry but I thought the `editor.formatOnType` should be disabled if we're going to use standardjs to do the format. It's not just a linter, it's also a formatter actually. It won't work with the built in editor formatter as far as I can see. Unless you can configure the built-in format rules, then standardjs can work as a linter only.
