### ISSUE TITLE
The flowtype plugins seems to be ignored in vscode

### ISSUE THREAD

**Issue by vlnk** [standard/vscode-standard#48]
- StandardJS version? 10.0.3
- VSCode version? 1.18.0 (ubuntu)
- StandardJS configuration? 
I used the package.json configuration for both the vscode setting and my webpack configuration:
`
  "standard": {
    "parser": "babel-eslint",
    "plugins": ["flowtype"]
  },
`
- What do you have in the `OUTPUT` panel? nothing but I have this message in the PROBLEMS panel:
![screenshot from 2017-11-12 17-35-18](https://user-images.githubusercontent.com/2649547/32704247-f5e8560e-c7cf-11e7-9b18-581d4fa2a76d.png)

Precisely, the standardjs linter ignores the colon used to declare the flow type but it doesn't understand the type itself.

**Comment by chenxsan** [comment]
It works fine in my test.

<img width="696" alt="screen shot 2017-11-13 at 4 45 39 pm" src="https://user-images.githubusercontent.com/1091472/32716746-1dbe6e58-c892-11e7-99e1-1b2b23661c72.png">

**Comment by vlnk** [comment]
ok, I have just done some test on Windows and the configuration is working by adding `"javascript.validate.enable": false` in the Workspace Settings of vscode (as it is recommended in the Flow setup for vscode). I thought it muted the standardjs linting in the editor but it seems to works well with both flow and standardjs.
By the way, thank you for your answer ;)

**Comment by chenxsan** [comment]
Actually we ask users of this extension to disable the built-in validator with `"javascript.validate.enable": false` too. You can check the readme file.

Anyway, glad you fix it.
