### ISSUE TITLE
Allow user to specify source command

### ISSUE THREAD

**Issue by Flet** [standard/vscode-standard#49]
Hello!

There is currently support for semistandard via the `standad.semistandard` setting, which is great!

However, it would be really nice to add a setting to specify a custom source command. This would allow the plugin to work with any `standard-engine` flavored command.

The main goal here is to allow folks to use https://github.com/standard/standardx with this plugin.

Doing it via a custom command enables even more flexibility for other commands ([doublestandard](https://github.com/flet/doublestandard) is always a good choice too).

**Comment by LinusU** [comment]
Would love to see automatic detection as well. Currently, when modifying any of e.g. Sindre's modules, basically every line shows up as an error. It would be cool if this module could detect `xo` in `devDependencies`, and then automatically use `xo` for that project.

**Comment by johnelliott** [comment]
One of our devs would like to do this too 👍

**Comment by xverges** [comment]
Would love to see #71 merged!
