### ISSUE TITLE
custom parser

### ISSUE THREAD

**Issue by pekeler** [standard/vscode-standard#5]
How can I use a custom parser? Setting `standard.options` in settings.json seems to be ignored.

```json
{
    "standard.autoFixOnSave": true,
    "standard.options": {
        "parser": "babel-eslint"
    }
}
```

Thanks

**Comment by chenxsan** [comment]
I have standard 8.6.0 installed globally, with babel-eslint@6 installed globally too, then setting `standard.options` in settings.json as you works for me.

**Comment by pekeler** [comment]
I don't have it installed globally, only locally in my project `--save-dev` which seems to work with the default parser. I'll try with a global install.

**Comment by pekeler** [comment]
Still not working. I have standard 8.6.0 and babel-eslint@6 installed globally. Using standard from the cmd-line says my code is fine. But the VSCode editor still complains about the use of the bind operator `::` with "[js] Expression expected.".

Any other ideas? Is there a way to run this extension more verbosely to see which parser it's using?

**Comment by chenxsan** [comment]
Could you paste some of your code?

This is what I get in my VSCode:

<img width="368" alt="screen shot 2016-12-24 at 9 11 27 am" src="https://cloud.githubusercontent.com/assets/1091472/21464472/0da13d3a-c9b9-11e6-978c-a9252d1dd823.png">

No, I don't think there's a way to check it. But it's easy to check it with some codes like class properties because only babel-eslint support it now.

Btw, you could paste your code into https://babeljs.io/repl to see if they are supported in babel now, or you might need plugins.

**Comment by denizdogan** [comment]
For what it's worth, I have the exact same problem as @pekeler. Installed babel-eslint@7.1.1 both locally and globally, with both NPM and Yarn, but VSCode acts like nothing happened. No errors, no warnings, no nothing...

```json
{
    ...
    "standard.enable": true,
    "standard.autoFixOnSave": true,
    "standard.options": {
        "parser": "babel-eslint"
    }
}
```

I also included `{ "standard": { "parser": "babel-eslint" } }` in my package.json to no avail.

**Comment by chenxsan** [comment]
@pekeler @denizdogan I just pushed 1.0.9 to marketplace, would you please test if the problem still exist?

**Comment by pekeler** [comment]
1.0.9 with VSCode 1.9.1 is still not working for me.

![standard9](https://cloud.githubusercontent.com/assets/42363/22986218/1031c00a-f368-11e6-86ac-24bbed21da4b.png)

**Comment by chenxsan** [comment]
This is what I got when running `standard` 8.6.0 and `babel-eslint` 7.1.1 locally with vscode-standardjs 1.0.9 on VSCode 1.9.1, macOS 10.12.2:

```js
var a = 5
class Bork {
  instanceProperty = a;
  boundFunction = () => {
    return this.instanceProperty
  }
  static staticProperty = 'babeliscool';
  static staticFunction = function () {
    return Bork.staticProperty
  }
}
let log = ::console.log
console.log(log)
```
<img width="460" alt="screen shot 2017-02-16 at 7 38 49 am" src="https://cloud.githubusercontent.com/assets/1091472/23000326/08a42914-f41b-11e6-826f-1d6644b0fc9d.png">
<img width="568" alt="screen shot 2017-02-16 at 7 39 05 am" src="https://cloud.githubusercontent.com/assets/1091472/23000327/096440d2-f41b-11e6-8621-03ca324906f9.png">

I also tested it with `standard` and `babel-eslint` globally installed, works too:

<img width="1005" alt="screen shot 2017-02-16 at 10 08 07 am" src="https://cloud.githubusercontent.com/assets/1091472/23004128/de785e52-f42f-11e6-85cd-2ffe601060d8.png">

Sorry I have no idea what could be wrong here.

**Comment by pekeler** [comment]
@chenxsan thank you for showing your settings.json. I didn't have this:
```json
"javascript.validate.enable": false
```
Adding it fixed this problem for me.

I never heard about this before. Might be useful to add to the docs.

**Comment by chenxsan** [comment]
Thanks for confirmation, fixed in https://github.com/chenxsan/vscode-standardjs/commit/bb633b47fd8da007f60b8a477b344a27e6be39c8
