### ISSUE TITLE
Disable rule globally

### ISSUE THREAD

**Issue by mech-tools** [standard/vscode-standard#50]
Is it possible to disable a rule globally?

```json
"eslintConfig": {
    "rules": {
      "standard/no-callback-literal": 0
    }
  }
```

I tried this configuration in package.json, but this doesn't work.
Since the no-callback-literal rule is broken, I would really like to disable it. It shows an error with the spread operator when it shouldn't. E.g:

```js
...
listeners.forEach(cb => {
  _.has(cb, '_once')
  ? cb._once(...args)
  : cb(...args) // eslint shows an error!
})
```

- StandardJS version?  1.2.0
- VSCode version? 1.18.1
- StandardJS configuration? standard
- What do you have in the `OUTPUT` panel? nothing (not a bug)

**Comment by chenxsan** [comment]
No, you can't do it in StandardJS.

How about renaming `cb` to something else like `cbb`? Looks like it could prevent the error in my test.

**Comment by mech-tools** [comment]
yeah, the names I should avoid are: cb, callback, next.
Thx!
