### ISSUE TITLE
Feature Request > Recursively fix formatting issues until there are no errors?

### ISSUE THREAD

**Issue by Jakobud** [standard/vscode-standard#51]
Currently, if there are several types of format issues in a JS file, you run the "Fix all auto-fixable problems" (or save the file if you have it set up like that) and it fixes just 1 of the issue types. You run it again and it fixes another issue type. And you repeat the process until no more auto-fixable problems are left.

Why don't you make this command fix stuff, then keep fixing more stuff, then fix more stuff etc until there are no more auto-fixable problems left? Just have it do it over and over automatically until it doesn't need to do it anymore.

The only potential issue I could see with this is, how does the extension know if there are any auto-fixable problems left or not? In other words how does it know to stop? I suppose it could always run a quick diff, comparing the content of the file before and after the command to see if any changes were made. If no changes were made, then it's done.

Any thoughts?

**Comment by chenxsan** [comment]
There's an opened issue on vscode-eslint here https://github.com/Microsoft/vscode-eslint/issues/154 you might want to check.

**Comment by theoludwig** [comment]
It seems like this issue doesn't exist anymore.
I installed `vscode-standardjs@1.4.0` and tested it with a file like that : 
```js
console.log('hello');
console.log('second semicolon');
```
When I ran "Fix all auto-fixable problems", it removes the two semicolons automatically without doing this 2 times.
```js
console.log('hello')
console.log('second semicolon')

```

If the issue appear again, please reopen.
