### ISSUE TITLE
format .vue file must install 3.x eslint-plugin-html

### ISSUE THREAD

**Issue by wangduanduan** [standard/vscode-standard#52]
# env
vscode: 1.18.1 
eslint-plugin-html@3.2.2
standard@10.0.3

`eslint-plugin-html` now is updated to 4.x, but it will not work well, you should write on the FAQ to install 3.x `eslint-plugin-html`

```
npm i -g eslint-plugin-html@3.2.2
```

**Comment by chenxsan** [comment]
Looks like `eslint-plugin-html`v4 requires at lease ESLint v4.7, and standard@10.0.3 still depends ESLint v3. I'll check it when standard 11 get released. Thanks for notice.

**Comment by doodlewind** [comment]
@chenxsan standard@11 is released now, any plan upgrading dependencies? Thanks.

**Comment by chenxsan** [comment]
@doodlewind This extension doesn't depend on `standard` directly, I thought it should work fine if you have `standard` 11 installed either globally or locally.

**Comment by doodlewind** [comment]
@chenxsan thanks, working fine for a fresh install with standard@latest and eslint-plugin-html@latest, guess this issue can be closed.
