### ISSUE TITLE
How to use with 'Format Document' command?

### ISSUE THREAD

**Issue by Deilan** [standard/vscode-standard#53]
Question's here.

How to invoke VS Code's 'Format Document' command with the extension?

**Comment by chenxsan** [comment]
No you can't do it in this extension.

We didn't register this formatting provider with [registerDocumentFormattingEditProvider](https://code.visualstudio.com/docs/extensionAPI/vscode-api#_languages).

**Comment by frederikhors** [comment]
Dear @chenxsan what to use for formatting?

**Comment by chenxsan** [comment]
@frederikhors Check the commands here https://github.com/standard/vscode-standardjs#commands

**Comment by frederikhors** [comment]
@chenxsan I'm referring to Windows (ALT+SHIFT+F) and similar MacOS command.

I think this extension doesn't have it, right?

Maybe I should go just with `OnSave` format.

**Comment by chenxsan** [comment]
@feross No, it doesn't. But you can config it yourself in VSCode `keybindings.json`：

```
[
  {"key": "alt+cmd+f", "command": "standard.executeAutofix"}
]
```

**Comment by baelter** [comment]
IMHO you should start using [registerDocumentFormattingEditProvider](https://code.visualstudio.com/docs/extensionAPI/vscode-api#_languages).
