### ISSUE TITLE
package.json "standard.parser" option not respected

### ISSUE THREAD

**Issue by egorovli** [standard/vscode-standard#54]
- StandardJS version: `11.0.0-beta.0`
- VSCode version: `1.19.1`
- StandardJS configuration (package.json):

```json
{
  "standard": {
    "parser": "babel-eslint"
  }
}
```

- What do you have in the `OUTPUT` panel?

```
[Info  - 12:48:12] JavaScript Standard Style server is running.
[Info  - 12:48:13] JavaScript Standard Style library loaded from: /Users/egorovli/Dev/project/node_modules/standard/index.js
```

- babel-eslint version: `8.2.1`

At some point standard started to throw errors like `state is undefined` for class properties, which made me update it to version `11.0.0-beta.0`. That particular error is resolved now, but then I noticed things like:

<img width="426" alt="screen shot 2018-01-09 at 13 07 26" src="https://user-images.githubusercontent.com/5165202/34715555-1b804c1e-f53e-11e7-8191-171d8b8dd17f.png">

Running `$ standard` (a binary) didn't throw any errors, so I presumed it was the extension. After reading some issues like this one #18 I found out that adding "standard.options.parser" option to VS Code's user settings fixes this behavior:

```json
"standard.options": {
  "parser": "babel-eslint"
}
```

Hence it turns out that the extension does not respect package.json now.

**Comment by chenxsan** [comment]
@egorovli Could you provide a small repo so I can test with?

**Comment by egorovli** [comment]
Sure thing: https://github.com/egorovli/vscode-standardjs-babel-eslint-issue-demo

It wouldn't be a problem really if I didn't break further linting.

**Comment by chenxsan** [comment]
Hi, here's what I have:

<img width="912" alt="screen shot 2018-01-09 at 8 05 02 pm" src="https://user-images.githubusercontent.com/1091472/34720067-67a7eebe-f578-11e7-9e9c-73494a97df8b.png">

Looks everything works fine.

Can you remove `node_modules` folder and run `yarn` again to see if it get fixed? Sometimes it might fix the problem.

**Comment by chenxsan** [comment]
Btw, what's your `standard` settings in VSCode User Settings, here's mine:

```json
"standard.validate": [
		"javascript",
		"javascriptreact",
		{ "language": "html", "autoFix": true }
	],
	"standard.usePackageJson": true,
	"standard.trace.server": "verbose",
	"standard.semistandard": false,
	"javascript.validate.enable": false,
```

**Comment by egorovli** [comment]
I have default settings for standard (no user-redefined settings):

```json
{
  "standard._legacyModuleResolve": false,
  "standard.autoFixOnSave": false,
  "standard.enable": true,
  "standard.nodePath": null,
  "standard.options": {},
  "standard.run": "onType",
  "standard.semistandard": false,
  "standard.trace.server": "off",
  "standard.usePackageJson": false,
  "standard.validate": [
    "javascript",
    "javascriptreact"
  ],
  "standard.workingDirectories": []
}
```

Plus user settings to disable built-in validation:

```json
{
  "javascript.validate.enable": false,
  "typescript.validate.enable": false
}
```

**Comment by egorovli** [comment]
Ok, setting `"standard.usePackageJson": true` also resolved the issue. I guess the comment is a bit misleading, it says "Activate JavaScript Standard Style only when it's presented in package.json", so it doesn't imply that it will ignore package.json if this setting is false.

**Comment by chenxsan** [comment]
When it's set to `false`, it will resolve the global installed `standard`. Since you don't have `standard` globally, so it failed. Yes I agree it's misleading, would u love to submit a pull request to update it?

**Comment by adrianmcli** [comment]
I just had this problem. I had `standard.usePackageJson` set to true in my VSCode settings, but I didn't have:

```
"standard.options": {
  "parser": "babel-eslint"
}
```

I thought that it would be able to look inside my `package.json` and find that I already declared:

```
"standard": {
    "parser": "babel-eslint"
  },
```

I think it's a bit un-intuitive that you have to do that since you already specify `usePackageJson` in the settings already. Can the README be updated or perhaps a fix for this?

# In summary

It looks like there are actually three steps required in total:

1. Set `"standard": { "parser": "babel-eslint" }` in `package.json`.
1. Set `"standard.options": { "parser": "babel-eslint" }` in VSCode settings.
2. Set `"standard.usePackageJson": true` in VSCode settings.

**Comment by chenxsan** [comment]
@adrianmcli Sorry for the inconvenience. But I think `"standard.usePackageJson": true` with `standard: { "parser": "babel-eslint"}` in `package.json` would be enough. `standard.options": { "parser": "babel-eslint" }` is for globally installed `standard`. Maybe we could remove those global settings to make thing clear, but I'm not sure if everyone will be happy.

**Comment by adrianmcli** [comment]
@chenxsan no need to say sorry, I just want to help by giving feedback 😃.

> I think `"standard.usePackageJson": true` with `standard: { "parser": "babel-eslint"}` in `package.json` would be enough.

It's strange, but I couldn't get it to work unless I had `"parser": "babel-eslint"` in both `package.json` and `standard.options`. I don't have `standard` installed globally.

**Comment by egorovli** [comment]
@adrianmcli I can confirm that it should work without `"standard.options": { "parser": "babel-eslint" }`. I have `"standard.usePackageJson": true` in VSCode's settings and `"standard": { "parser": "babel-eslint" }` in package.json, and it works.
