### ISSUE TITLE
Depends on Workspace path not relative to the package settings.

### ISSUE THREAD

**Issue by reggi** [standard/vscode-standard#56]
If I have the following tree.

```
.
└── example-standard
    └── module-itself
        ├── index.js
        └── package.json
```

And when I open the workspace as `example-standard` It does not work correctly, where as If I open it as `module-itself` it works.

Can I fix this in the settings?

![image 2018-01-17 11-37-35](https://user-images.githubusercontent.com/296798/35054595-e8fd8872-fb7a-11e7-9c87-9f1a444642e4.png)

**Comment by chenxsan** [comment]
So I think you have `standard` installed under `module-itself`? Then it won't work. You can't resolve a module in nested folder. If there are many of them, it will become Inefficient.
