### ISSUE TITLE
Not autofixing

### ISSUE THREAD

**Issue by imcodingideas** [standard/vscode-standard#58]
- StandardJS version?
11.0.1
- VSCode version?
1.23.1
- StandardJS configuration?
I don't have any plugins enabled other than `chenxsan.vscode-standardjs` and my settings.json only contains this:

```javascript
{
  "standard.run": "onType",
  "standard.autoFixOnSave": true,
  "standard.enable": true,
}
```
- What do you have in the `OUTPUT` panel?

[Info  - 12:19:44] JavaScript Standard Style library loaded from: /node_modules/standard/index.js
/admin/src/components/auth/file.js ignored.

**Comment by chenxsan** [comment]
Hi, is it your first time trying this extension or it just suddenly won't work anymore?

Do you have

```
"javascript.validate.enable": false,
```
in `settings.json`?

**Comment by imcodingideas** [comment]
update

**Comment by chenxsan** [comment]
@imcodingideas Does it work for you after adding `"javascript.validate.enable": false,` to your settings.json?

**Comment by chenxsan** [comment]
Seems those files were ignored by Standard for some settings you have. You might want to check https://standardjs.com/#how-do-i-ignore-files

Btw, where do you put your project? Do you have it under `/`?

**Comment by jeffersonpillejera** [comment]
@chenxsan  This happens to me when my project or js file resides in WSL Ubuntu in my Win10 OS

`OUTPUT` Tab
[Info  - 8:28:24 pm] JavaScript Standard Style server stopped.
[Info  - 8:28:27 pm] JavaScript Standard Style server is running.
[Info  - 8:28:34 pm] JavaScript Standard Style library loaded from: \\wsl.localhost\Ubuntu\home\user\empty-project\node_modules\standard\index.js
\\wsl.localhost\Ubuntu\home\user\empty-project\app.js ignored.

But if I open my project in windows local filesystem, it works fine.
