### ISSUE TITLE
I'd really like to see testing files support

### ISSUE THREAD

**Issue by forrestblade** [standard/vscode-standard#59]
I just want to see this exstension support testing files.

For instance, with enzyme testing and jest I often use `describe` and `it` but I always get back errors for it being undefined in the file. this is obviously not a problem because there is not a need to define the `describe` and `it`

```
_describe_('App', () => {
  it('should exist with a `div`', () => {
    const component = shallow(<App />)

    expect(component.is('div')).to.be.true()
  })

  _it_('should contain a `Header`', () => {
    const component = shallow(<App />)
    const header = component.find('Header')

    expect(header.exists()).to.be.true()
  })

  _it_('should contain three `Post` component', () => {
    const component = shallow(<App />)
    
    expect(component.find('Post')).to.have.length(3)
  })
})
```

**Comment by chenxsan** [comment]
Standardjs already support it with [env](https://standardjs.com/#what-about-mocha-jasmine-qunit-etc)

**Comment by forrestblade** [comment]
this is exactly what I was trying to figure out, I looked everywhere and I must've looked right over it haha
thank you
