### ISSUE TITLE
VS Code's Format document falls back to default formatter instead of Standard

### ISSUE THREAD

**Issue by egorovli** [standard/vscode-standard#60]
- StandardJS version? `11.0.1`

- VSCode version `1.23.0`

- StandardJS configuration?

In `package.json`:
```json
{
  "standard": {
    "parser": "babel-eslint",
    "env": [
      "jest"
    ]
  }
}
```

In VS Code prefs:
```json
{
  "javascript.validate.enable": false,
  "standard.usePackageJson": true,
  "standard.validate": [
    "javascript",
    "javascriptreact"
  ]
}
```
- What do you have in the `OUTPUT` panel?
Output panel is empty

I've always used "Format document" <kbd>⌥ Option</kbd>+<kbd>⇧ Shift</kbd>+<kbd>F</kbd> to format `.js` files with Standard, but it seems like with the last VS Code update it _sometimes_ stops working. Reloading window helps, but not for a long time. See video:

https://www.dropbox.com/s/wkigo5huor64xp3/Standard%20works%20only%20after%20VS%20Code%20reload.mp4?dl=0

**Comment by chenxsan** [comment]
I don't think this extension support `Format document`. You could check https://github.com/standard/vscode-standardjs/issues/9.

**Comment by egorovli** [comment]
@chenxsan thanks, I'll switch to "Fix all auto-fixable problems". Weird though, that it used to work before ¯\\\_(ツ)_/¯
