### ISSUE TITLE
Defualt formatting prompt 'Missing space before function parentheses. (space-before-function-paren)' error

### ISSUE THREAD

**Issue by qiansen1386** [standard/vscode-standard#61]
- StandardJS version?1.2
- VSCode version?1.23.1
- StandardJS configuration? default
- What do you have in the `OUTPUT` panel?nothing wrong.
![image](https://user-images.githubusercontent.com/1759658/40769155-d963c056-64e9-11e8-80e1-1a658d3fafd5.png)
![image](https://user-images.githubusercontent.com/1759658/40769179-e73c713c-64e9-11e8-8150-91e498e459b8.png)

**Comment by chenxsan** [comment]
The latest standardJS version is [11.0.1](https://github.com/standard/standard/releases)

**Comment by qiansen1386** [comment]
@chenxsan So sorry, I thought it's the version of the extension. The version of npm package is standard@11.0.1.

**Comment by chenxsan** [comment]
Do you mean after you run this command:
<img width="730" alt="image" src="https://user-images.githubusercontent.com/1091472/40815683-b77364c4-657a-11e8-9007-6dd2579d2983.png">

You're still getting the problem?  I've tested in my vscode, everything looks fine.

<img width="786" alt="image" src="https://user-images.githubusercontent.com/1091472/40815703-dc905a64-657a-11e8-844f-2a341b7a4c76.png">

**Comment by qiansen1386** [comment]
Oh, I see, I was running the default formatting command, instead of your one.
I thought VS code can use StandarJS as default foramatter. Is there a way for us to config this command as default formatting behavior?

**Comment by chenxsan** [comment]
No, there's no way at this time. Releated issue here https://github.com/standard/vscode-standardjs/issues/9
