### ISSUE TITLE
Adding "html" to standard plugins breaks validation

### ISSUE THREAD

**Issue by trevorhreed** [standard/vscode-standard#63]
I'm trying to enable standardjs validation for javascript and vue files. Following the instructions [here](https://github.com/standard/vscode-standardjs#faq), I added the following reference in my VSCode settings file:

```
"standard.options": {
  "plugins": ["html"]
}
```

However, this not only doesn't make validation work in *.vue files, but also stops validation from working in *.js files.

- StandardJS version? `11.0.1`
- VSCode version? `1.24.0`
- StandardJS configuration?

```
    "standard.validate": [
        "javascript",
        "html"
    ],
    "standard.options": {
        "plugins": ["html"],
        "ignore": [
            "node_modules/**"
        ]
    },
    "files.associations": {
        "*.vue": "html"
    }
```

- What do you have in the `OUTPUT` panel? `Nothing`

**Comment by chenxsan** [comment]
You should got something like this under `OUTPUT` panel:

<img width="1297" alt="image" src="https://user-images.githubusercontent.com/1091472/41390793-d1197d2e-6fc9-11e8-98cd-2d139655b2d2.png">

**Comment by yf287** [comment]
You can find if module 'standard' and 'eslint-plugin-html' are under the same folder, if not, standardjs won't work
