### ISSUE TITLE
Does not exist for code-insiders

### ISSUE THREAD

**Issue by brianmhunt** [standard/vscode-standard#65]
With VS Code Insiders this extensions is not found.  From the command line:

```bash
$ code-insiders --install-extension vscode-standardjs
Extension 'vscode-standardjs' not found.
Make sure you use the full extension ID, including the publisher, eg: ms-vscode.csharp
```

**Comment by chenxsan** [comment]
Seems you need to include the publisher prefix when installing it from command line, please try:

```
code-insiders --install-extension chenxsan.vscode-standardjs
```

**Comment by brianmhunt** [comment]
Thanks @chenxsan .  That seems to have worked.  For no apparent reason, the plugin remains missing from the list of extensions when one is searching for "standardjs".

**Comment by chenxsan** [comment]
Just search `JavaScript standard style` or `standard`, seems the marketplace only support searching title.

**Comment by brianmhunt** [comment]
Thanks.  I think many folks may search for "standardjs"; not sure if updating the title is viable, but it would certainly have saved me having to write this issue and bother you. :wink:

**Comment by chenxsan** [comment]
@brianmhunt That's a great suggestion. I'll update the title.
