### ISSUE TITLE
昨天插件更新后，插件就不运行了

### ISSUE THREAD

**Issue by wangbinxiang** [standard/vscode-standard#68]
- StandardJS version?
1.2.2
- VSCode version?
1.25.1 
- StandardJS configuration?

```
"standard.enable": true,
"standard.autoFixOnSave": true,
"standard.run": "onType",
```

- What do you have in the `OUTPUT` panel?
  昨天插件更新后，插件就不运行了
  现在是OUTPUT面板里没有 "JavaScript Standard Style " 这一项
  我确定standard.enable设置为true了
  之前一直好着呢，大概是昨天突然不运行了。

![wechatimg43](https://user-images.githubusercontent.com/2654774/43368664-62dc1072-9393-11e8-96e9-3665e713fbb2.png)

**Comment by wangbinxiang** [comment]
还有 运行 standard的命令会提示命令没有找到
![1532883563578](https://user-images.githubusercontent.com/2654774/43368704-0fecffe2-9394-11e8-8df2-91cc68c4b52c.jpg)
![1532883586459](https://user-images.githubusercontent.com/2654774/43368695-ed0a01be-9393-11e8-9765-2d7eaed321f3.jpg)

插件肯定也是安装了的
![1532883598924](https://user-images.githubusercontent.com/2654774/43368698-f5d98792-9393-11e8-8847-d26680f0e14e.jpg)

**Comment by chenxsan** [comment]
Just released a new version to fix it.

**Comment by wangbinxiang** [comment]
update to version 1.2.3.  It's work!
Great job!
Low English, lol!
