### ISSUE TITLE
VSCode extension can't found Standard installed globally

### ISSUE THREAD

**Issue by davibusanello** [standard/vscode-standard#70]
- StandardJS version? 11.0.1
- VSCode version? 1.26.0
- StandardJS configuration? Default
- What do you have in the `OUTPUT` panel?
```
Failed to load the JavaScript Standard Style library for the document test-project/tests.js

To use JavaScript Standard Style please install JavaScript Standard Style by running 'npm install standard' in the workspace folder test-project
or globally using 'npm install -g standard'. You need to reopen the workspace after installing JavaScript Standard Style.

Alternatively you can disable JavaScript Standard Style for the workspace folder test-project by executing the 'Disable JavaScript Standard Style' command.
```

I am using yarn as package manager and have installed standard globally.

If I call standard in Terminal works:
```
standard
standard: Use JavaScript Standard Style (https://standardjs.com)
standard: Run `standard --fix` to automatically fix some problems.
  test-project/tests.js:3:18: Newline required at end of file but not found.
```

**Comment by davibusanello** [comment]
It works with npm.
In another vscode's extensions have the option to set which is the package manager I'm using then don't have this. It could be an enhancement

**Comment by anqur** [comment]
- I met this same issue in this environment
    + Windows 10
    + Node v11.8.0
    + NPM v6.7.9 (I deleted the bundled `npm` with Node's Windows `.msi` installation, using the one via `npm i -g npm@latest` instead)
    + `standard` v12.0.1, *globally installed*
    + `vscode-standardjs` v1.2.3
- I got `standard command not found` output from `OUTPUT` panel
```
[Info  - 6:02:11 PM] Failed to load the JavaScript Standard Style library for the document c:\Users\***\Desktop\foo.js
To use JavaScript Standard Style for single JavaScript file install standard globally using 'npm install -g standard'.
You need to reopen VS Code after installing standard.
```
- How could I debug this issue and is it really related to `vscode-eslint`?  And what is the current status of that foreign extension?

**Comment by theoludwig** [comment]
It is related to this line : https://github.com/standard/vscode-standardjs/blob/1fbb5e8b50abb83e7f198cfba11e56964d876ea3/server/src/server.ts#L748

JSDoc of the method inside `vscode-languageserver` : 
```js
/**
 * Resolve the global npm package path.
 * @deprecated Since this depends on the used package manager and their version the best is that servers
 * implement this themselves since they know best what kind of package managers to support.
 * @param tracer the tracer to use
 */
```

In addition that it is a deprecated method, it only checks for `npm` package path, not for `yarn` for example.
If anyone know how to fix it, we're grateful of PRs. :+1:

**Comment by Sai1919** [comment]
Might help, we can actually edit the "standard.nodePath" in the settings.json directly to the directory where standard npm module is installed on the machine. For me this solved the issue.

**Comment by AnzenKodo** [comment]
I have install globally and locally also then also issus don't resolve.

```
[Info  - 6:40:32 am] JavaScript Standard Style server stopped.
[Info  - 6:40:34 am] JavaScript Standard Style server is running.
[Info  - 6:40:37 am] JavaScript Standard Style library loaded from: /home/kurama/Documents/Projects/Node JS/node_modules/standard/index.js
[Info  - 6:40:38 am] Failed to load the JavaScript Standard Style library for the document /home/kurama/.config/Code/User/settings.json
To use JavaScript Standard Style for single JavaScript file install standard globally using 'npm install -g standard'.
You need to reopen VS Code after installing standard.
```

**Comment by Eomm** [comment]
I'm having the same issue, @AmanKodo did you find some workaround?

**Comment by AnzenKodo** [comment]
@Eomm uninstalling & reinstalling the extension should work.

or add this to your `settings.json` in vscode
```
"standard.nodePath": "<global npm package path>"
```

**Comment by vanokhin** [comment]
```json
"standard.nodePath": "/usr/local/lib/node_modules"
```
The code above added to `settings.json` fixed the issue for me on Mac OS
