### ISSUE TITLE
save .vue file  auto format isn't expectation result

### ISSUE THREAD

**Issue by yzStrive** [standard/vscode-standard#72]
- StandardJS version?
12.0.0
- VSCode version?
1.26.1
- StandardJS configuration?
--
```
{
  "standard.validate": [
    "javascript",
    "javascriptreact",
    {
      "language": "vue",
      "autoFix": true
    }
  ],
  "standard.options": {
    "plugins": ["vue"]
   },
  "standard.autoFixOnSave": true
}
```
- What do you have in the `OUTPUT` panel?

format before [expectation result]
```js
<script>
import { HelloWorld } from 'components'

export default {
  name: 'Home',
  components: {
    HelloWorld
  }
}
</script>
```
save format later
```js
<script>
import { HelloWorld } from "components";

export default {
  name: "Home",
  components: {
    HelloWorld
  }
};
</script>
```

**Comment by SolT31** [comment]
try https://github.com/standard/vscode-standardjs/issues/35#issuecomment-462118328

**Comment by SolT31** [comment]
Try https://github.com/standard/vscode-standardjs/issues/35#issuecomment-462118328

Perhaps still prettier is configured on autofix

**Comment by theoludwig** [comment]
Duplicate of #35
