### ISSUE TITLE
Disable if local version is not detected

### ISSUE THREAD

**Issue by Kikobeats** [standard/vscode-standard#73]
Hello! 🙂

I want to disable the plugin just when `standard` is not detected as dependency.

It's something that is configurable in the atom version of this plugin:

<img width="641" alt="screenshot 2018-11-11 at 21 39 14" src="https://user-images.githubusercontent.com/2096101/48318032-c38a3700-e5fa-11e8-9104-573888547182.png">

I think it's related to https://github.com/standard/vscode-standardjs/issues/21, but just disable it if local version is not detected.

**Comment by chenxsan** [comment]
There's a `usePackageJson` option https://github.com/standard/vscode-standardjs#plugin-options, you can set it `true`.

**Comment by Kikobeats** [comment]
Thanks!
