### ISSUE TITLE
format wrong with jsx

### ISSUE THREAD

**Issue by yf287** [standard/vscode-standard#74]
- StandardJS version?
v12.0.1

- VSCode version?
v1.28.2

- StandardJS configuration?

```
"standard.validate": [
    "javascript",
    "javascriptreact",
    {
      "language": "vue",
      "autoFix": true
    },
    {
      "language": "html",
      "autoFix": true
    }
  ],
  "standard.options": {
    "parser": "babel-eslint",
    "plugin": ["html"],
    "global": [
      "fetch",
      "localStorage",
      "sessionStorage",
      "location"
    ]
  },
```

- What do you have in the `OUTPUT` panel?
/Users/lianjia/Documents/icode/company-static/src/client/pages/admin/order/detail/index.jsx:58:8: Expected indentation of 4 space characters but found 0.
  /Users/lianjia/Documents/icode/company-static/src/client/pages/admin/order/detail/index.jsx:59:1: Expected indentation of 7 spaces but found 2.
  /Users/lianjia/Documents/icode/company-static/src/client/pages/admin/order/detail/index.jsx:59:3: Expected indentation of 4 space characters but found 2.
  /Users/lianjia/Documents/icode/company-static/src/client/pages/admin/order/detail/index.jsx:60:1: Expected indentation of 9 spaces but found 2.
  /Users/lianjia/Documents/icode/company-static/src/client/pages/admin/order/detail/index.jsx:60:3: Expected indentation of 4 space characters but found 2.
  /Users/lianjia/Documents/icode/company-static/src/client/pages/admin/order/detail/index.jsx:61:1: Expected indentation of 9 spaces but found 2.
  /Users/lianjia/Documents/icode/company-static/src/client/pages/admin/order/detail/index.jsx:61:3: Expected indentation of 4 space characters but found 2.
  /Users/lianjia/Documents/icode/company-static/src/client/pages/admin/order/detail/index.jsx:62:1: Expected indentation of 11 spaces but found 2.
  /Users/lianjia/Documents/icode/company-static/src/client/pages/admin/order/detail/index.jsx:62:3: Expected indentation of 4 space characters but found 2.

I set autoFixOnSave,but when I save *.jsx, the file will be formatted wrong, like this:
![image](https://user-images.githubusercontent.com/18239400/48597149-41519800-e997-11e8-8529-164a0f347b69.png)

**Comment by chenxsan** [comment]
Will [`Fix all auto-fixable problems`](https://github.com/standard/vscode-standardjs#commands) command fix your problem?

**Comment by yf287** [comment]
No, using Fix all auto-fixable problems command has the same result with "standard.autoFixOnSave": true.

**Comment by chenxsan** [comment]
I have no idea what's going on here, everything looks fine on my computer:

<img width="914" alt="image" src="https://user-images.githubusercontent.com/1091472/48602826-66520500-e9af-11e8-8254-050e8ae1a65b.png">

**Comment by yf287** [comment]
Emmm, I found a new condition: these files which got wrong format indented using 2 or 4 tabs before. The same result will occur when I change using tabs to spaces manually.

**Comment by SolT31** [comment]
try eslint-plugin-html@4.0.6

I helped solve the problem with vue files

**Comment by feross** [comment]
This is fixed in `standard` 15.
