### ISSUE TITLE
Extension not working properly

### ISSUE THREAD

**Issue by jorgev259** [standard/vscode-standard#75]
- StandardJS version? 12.0.1
- VSCode version? 1.29.1 (sytem version)
- StandardJS configuration? default
- What do you have in the `OUTPUT` panel? 
`[Info  - 10:19:02 AM] JavaScript Standard Style server is running.
[Info  - 10:19:03 AM] JavaScript Standard Style library loaded from: C:\Users\ControlSoft\AppData\Roaming\npm\node_modules\standard\index.js`

Enabled standardjs on the project, tied reloading and reinstalling the extension but it doesnt work. Most problems arent detected and it doesnt lint the file when using the Fix command

**Comment by chenxsan** [comment]
Have you ever disabled the built-in VSCode validator by setting `"javascript.validate.enable": false` in your VSCode settings.json?

**Comment by jorgev259** [comment]
yes, i did it and reloaded the app. Same result

**Comment by bouvin** [comment]
Bump.
I am seeing much the same behaviour with standard 12.0.3, VSC 1.33.1, StandardJS 1.2.0 on macOS 10.14.4. Brew installed Node.js 12.1.0. Standard installed globally.
```
    [Info  - 10:35:03 AM] JavaScript Standard Style server is running.
    [Info  - 10:35:03 AM] JavaScript Standard Style library loaded from: /usr/local/lib/node_modules/standard/index.js
```
I have disabled javascript.validate. I have also tried using eslint instead, which works as expected in VSC.

**Comment by theoludwig** [comment]
Is it still the case in newer versions ? If it is please reopen this issue.

**Comment by jfoclpf** [comment]
In my case I had to install standard globally `npm i -g standard` and define the path to node (in my case, ubuntu, `"standard.nodePath": "/usr/bin/node"`, in linux based systems just run in cli `which node` to know the path)
