### ISSUE TITLE
Unable to find local standard when in dependencies and not devDependencies

### ISSUE THREAD

**Issue by rstrand** [standard/vscode-standard#79]
- StandardJS version? 1.13.0
- VSCode version? 1.30.2
- StandardJS configuration? Use local package.json
- What do you have in the `OUTPUT` panel?
```
[Info  - 11:45:24] JavaScript Standard Style server is running.
[Info  - 11:45:24] no standard in package.json
[Info  - 11:45:24] no standard in package.json
[Info  - 11:45:24] JavaScript Standard Style library loaded from: {path_removed}/node_modules/standard/index.js
```

When standard is installed as a regular dependency rather than a dev dependency it is not found correctly.

**Comment by theoludwig** [comment]
`standard` should not be installed in `dependencies`, could you tell me your use-case ? @rstrand 
I don't think it is necessary to also check if `standard` is in `dependencies`, it should be always in `devDependencies`.
