### ISSUE TITLE
执行Fix all auto-fixable problems 时vscode报错

### ISSUE THREAD

**Issue by Tibbersss** [standard/vscode-standard#8]
![image](https://cloud.githubusercontent.com/assets/10751521/21773088/acb94504-d6c8-11e6-9273-b3f54b9bd395.png)

**Comment by chenxsan** [comment]
不清楚是什么情况，如果能贴上代码是最好的。

你也可以试试最新的 1.0.9 版本，看看这个问题是否还存在。
