### ISSUE TITLE
Command not found errors pop up

### ISSUE THREAD

**Issue by achou11** [standard/vscode-standard#80]
- StandardJS version? 12.0.1
- VSCode version? 1.31.0
- StandardJS configuration? Default
- What do you have in the `OUTPUT` panel? Nothing

Anytime I try to execute the extension commands e.g. 'JavaScript Standard Style: Fix all auto-fixable Problems', I get the following error: `command 'standard.executeAutofix' not found`. Same thing happens with the other commands. Tried reinstalling both Standard (globally) and the extension but that hasn't fixed anything. I apologize if this issue has been addressed already. Thanks!

**Comment by perguth** [comment]
Same problem when using this extension with https://github.com/cdr/code-server

**Comment by theoludwig** [comment]
It seems like this issue doesn't exist anymore.
If the issue appear again, please reopen.
