### ISSUE TITLE
conflict with Create React App ESLint version

### ISSUE THREAD

**Issue by dcsan** [standard/vscode-standard#81]
When I install standard in a repo which also uses Create React App, I get the error below about conflicting versions of ESLint.

my repo is structured like this:

```
/package.json
    /client/package.json
    /server/package.json
```

when I add standard at the root level, I will get the eslint error and cannot build the react app.
however, standard is functioning well.

when I add standard into any of the `/client` or `/server` directories, it doesn't seem to run, perhaps I could get around this by adding subfolders as new worksspaces as noted in the docs about dealing with mono-repos, but this seems like a hassle.

- StandardJS version?
``` ✗ npm standard --version
6.8.0
```
- VSCode version?
latest

- StandardJS configuration?
basic

- What do you have in the `OUTPUT` panel?
[Info  - 12:24:49 PM] JavaScript Standard Style server is running.
[Info  - 12:24:50 PM] JavaScript Standard Style library loaded from: /Users/dc/dev/rikai/rabbit/server/node_modules/standard/index.js

----
## error message after trying to build with `react-scripts build`

$ yarn build
yarn run v1.13.0

$ npm run clean && react-scripts build && mv build ../server/public/
npm WARN lifecycle The node binary used for scripts is /var/folders/wl/fsxhspwn0351_lx_55rkwgwc0000gn/T/yarn--1551846013151-0.6910341591898146/node but npm is using /usr/local/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> react-pusher@0.1.0 clean /Users/dc/dev/rikai/rabbit/client
> rm -rf ../server/public/build

There might be a problem with the project dependency tree.
It is likely not a bug in Create React App, but something you need to fix locally.

The react-scripts package provided by Create React App requires a dependency:

  "eslint": "5.12.0"

Don't try to install it manually: your package manager does it automatically.
However, a different version of eslint was detected higher up in the tree:

  /Users/dc/dev/rikai/rabbit/node_modules/eslint (version: 5.4.0)

Manually installing incompatible versions is known to cause hard-to-debug issues.

If you would prefer to ignore this check, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That will permanently disable this message but you might encounter other issues.

To fix the dependency tree, try following the steps below in the exact order:

  1. Delete package-lock.json (not package.json!) and/or yarn.lock in your project folder.
  2. Delete node_modules in your project folder.
  3. Remove "eslint" from dependencies and/or devDependencies in the package.json file in your project folder.
  4. Run npm install or yarn, depending on the package manager you use.

In most cases, this should be enough to fix the problem.
If this has not helped, there are a few other things you can try:

  5. If you used npm, install yarn (http://yarnpkg.com/) and repeat the above steps with it instead.
     This may help because npm has known issues with package hoisting which may get resolved in future versions.

  6. Check if /Users/dc/dev/rikai/rabbit/node_modules/eslint is outside your project directory.
     For example, you might have accidentally installed something in your home folder.

  7. Try running npm ls eslint in your project folder.
     This will tell you which other package (apart from the expected react-scripts) installed eslint.

If nothing else helps, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That would permanently disable this preflight check in case you want to proceed anyway.

P.S. We know this message is long but please read the steps above :-) We hope you find them helpful!

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by dcsan** [comment]
installing standard globally didn't work either.

in case anyone else has the problem, I was able to get it working with adding client and server as separate folders to the workspace, but now I have a duplicated layout

![image](https://user-images.githubusercontent.com/514002/53856722-2d957480-400e-11e9-8203-2b7273d2df6f.png)

**Comment by ashwinsoni** [comment]
> If nothing else helps, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That would permanently disable this preflight check in case you want to proceed anyway.

@dcsan You could try creating a `.env` in client with below content 

```SKIP_PREFLIGHT_CHECK=true```

Worked for me!!

[More details here](https://github.com/facebook/create-react-app/issues/5247#issuecomment-427221678)

**Comment by lll000111** [comment]
By the way &mdash; the tracking issue for this for "create-react-app" is https://github.com/facebook/create-react-app/issues/5247 &mdash; consider upvoting. The problem of the solution is above is it disables *everything* when all you want is to ignore this silly eslint-version non-issue.

**Comment by haykerman** [comment]
So if `SKIP_PREFLIGHT_CHECK=true` is not a solution, but rather a hack, and reusing eslint from react-scripts package is a bad idea, what is that one correct solution to this?

**Comment by seong7** [comment]
> @dcsan You could try creating a `.env` in client with below content
> 
> `SKIP_PREFLIGHT_CHECK=true`
> 
> Worked for me!!

But hasn't this solution cuased any 'hard-to-debug' issue as mentioned below.

> Manually installing incompatible versions is known to cause hard-to-debug issues.

**Comment by ashwinsoni** [comment]
Not at all @seong7 
It won't create a problem unless we manually install eslint version which is incompatible to Create React App's own eslint version

**Comment by feross** [comment]
We've updated the version of ESLint in `standard` to the latest, so this issue is likely resolved.

**Comment by kirtikapadiya** [comment]
https://github.com/expo/expo/issues/22061
