### ISSUE TITLE
standard.autoFixOnSave does not work with typescript

### ISSUE THREAD

**Issue by CodeDraken** [standard/vscode-standard#82]
- StandardJS version?
12.0.1

- VSCode version?
1.32.2

- StandardJS configuration?
```json
"standard": {
    "parser": "typescript-eslint-parser",
    "plugins": [
      "typescript"
    ]
  }
```

- What do you have in the `OUTPUT` panel?
Nothing.

VS Code settings.json
```json
"standard.enable": true,
"standard.validate": [
    "javascript",
    "javascriptreact",
    "typescript"
  ],
"standard.autoFixOnSave": true
```

Manually doing `standard --fix` works. The extension does properly highlight errors in typescript files but does not auto fix on save with the setting enabled.

**Comment by ryanpcmcquen** [comment]
Try this: https://github.com/numso/prettier-standard-vscode

**Comment by jzlai** [comment]
the validate object has to look like this:

```json
"standard.validate": [
    "javascript",
    "javascriptreact",
    {
      "language": "typescript",
      "autoFix": true
    }
  ]
```

However, I opened a PR #96 which enables typescript by default.

**Comment by klvfn** [comment]
> the validate object has to look like this:
> 
> ```json
> "standard.validate": [
>     "javascript",
>     "javascriptreact",
>     {
>       "language": "typescript",
>       "autoFix": true
>     }
>   ]
> ```
> 
> However, I opened a PR #96 which enables typescript by default.

this doesn't work for me, any other idea?

**Comment by jzlai** [comment]
Are you using the version from the store? If so, you need to build it yourself, since that version is outdated.

**Comment by feross** [comment]
The store has the latest version now! See: https://github.com/standard/vscode-standardjs/issues/121#issuecomment-721937726
