### ISSUE TITLE
autoFixOnSave not working!

### ISSUE THREAD

**Issue by huanghanyue** [standard/vscode-standard#83]
- StandardJS version?  12.0.1
- VSCode version?  1.32.1
- StandardJS configuration? 
![image](https://user-images.githubusercontent.com/16572115/54902795-40b4a980-4f15-11e9-8886-6d31d1d2070d.png)

- What do you have in the `OUTPUT` panel?
![image](https://user-images.githubusercontent.com/16572115/54902808-48744e00-4f15-11e9-9cbb-1e77f729d1e3.png)

**Comment by nitinja** [comment]
I experienced the same thing - autofix on save not working.

**Comment by ryanpcmcquen** [comment]
This one actually works: https://github.com/numso/prettier-standard-vscode

**Comment by jsumners** [comment]
@feross does the core team still maintain this plugin? It doesn't look like it has been touched in months and this issue has not received any acknowledgement.

**Comment by feross** [comment]
Hi everyone, I'm not a user of Visual Studio Code so I don't know where to start to fix this, but if one of you wants to dig in and send a pull request, I'll be happy to merge it. (I'm not currently checking GitHub notifications regularly because I'm in graduate school so please email me if I don't see the PR)

**Comment by mesqueeb** [comment]
+1 for autofix on save not working on VSCode...

**Comment by liub1934** [comment]
升级版本后不管用了，目前版本vs版本：1.35

**Comment by feross** [comment]
This issue is still open if someone wants to tackle it ;)

**Comment by jsumners** [comment]
I suspect no one commenting on this issue knows the code well enough to work on it. Personally, I don't have the time _and_ I don't write TypeScript.

**Comment by ryanpcmcquen** [comment]
I have since switched to Sublime, the packages seem to be of a higher quality overall for Sublime and the editor is way snappier as well.

**Comment by mesqueeb** [comment]
The only thing that worked for me was using regular ESLint, and just use the standard config for that.
Then I had to set my VSCode settings to this:
```json
  "javascript.validate.enable": false,
  "typescript.format.enable": false,
  "vetur.validation.style": false,
  "vetur.validation.template": false,
  "editor.insertSpaces": true,
  "editor.tabSize": 2,
  "editor.formatOnSave": false,
  "eslint.autoFixOnSave": true,
  "eslint.validate": [
    "javascript",
    "javascriptreact",
    {
      "language": "vue",
      "autoFix": true
    },
  ],
```
that was the only setup that worked for me **which actually auto fixes my formatting on save**!
good luck!! 😉 

I believe if this package ever works, it might make the setup easier & usable without requiring an eslint setup?

**Comment by wouterds** [comment]
Doesn't seem to do anything at all for me. No warnings, errors or auto fixing.

**Comment by mesqueeb** [comment]
@wouterds did you install the plugins? You'll need the `eslint` VSCode plugin and have the correct ESLint setup in your `.eslintrc` in the root folder of your project.

**Comment by DeckardCainCN** [comment]
Hi. If you use VSCode, you should check the following steps:
1. Install the StandardJS in VSCode Extensions Market.
2. Install standard: `npm install -g standard/semistandard`
3. Configure your VSCode settings like that:
 
    {
          "editor.formatOnSave": true,
          "javascript.validate.enable": false,
          "standard.autoFixOnSave": true
      }
4. Restart your VSCode

**Comment by jsumners** [comment]
Building on @mesqueeb's suggestion, this is what I did to get this working:

1. Uninstall this plugin
2. Install the eslint plugin -- https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint
3. In my project: `npm install --save-dev eslint eslint-config-standard eslint-plugin-standard eslint-plugin-promise eslint-plugin-import eslint-plugin-node` (ugh, just "standard" was so much nicer)
4. Add `{ "extends": "standard" }` in a `.eslintrc` to my project
5. In my vscode `settings.json`:
    ```json
    "[javascript]": {
        "editor.defaultFormatter": "dbaeumer.vscode-eslint",
        "editor.codeActionsOnSave": {
          "source.fixAll.eslint": true
        }
      }
    ```

**Comment by jsumners** [comment]
Further follow-up:

It seems all that is required for step 3 is `npm install --save-dev standard`. This will cause the configuration in steps 4 and 5 to work correctly in conjunction with one another.

**Comment by matt6frey** [comment]
I am not sure if anybody has tried this in 2020 yet, but I recently installed VSCode and started a Vue project, using eslint & prettier. 

I have the eslint extension for vscode, eslint install globally (`npm i eslint -g`), and an `eslintrc.js` file too. My system is Windows 10.


**I used:**

- `CTRL + SHIFT + P`, typed settings (select .json ext)
- added ```
   {
       "editor.tabSize": 2,
       "editor.codeActionsOnSave": {
            "source.fixAll.eslint": true
       }
   }```

I didn't need to close & re-open. Hopefully that helps out. My VS code version is pretty new also. `Eslint > format` is off.

**Comment by JSoon** [comment]
For me, I have solved it exactly by the following configs:
```js
"eslint.validate": [
    {
        "language": "vue", // Whatever language you are using
        "autoFix": true // This is vital, because the autofixing won't work without this even if you have the right settings below
    }
],
// https://github.com/microsoft/vscode-eslint/issues/600#issuecomment-469211948
"eslint.autoFixOnSave": true,
"files.autoSave": "off", // no fix on save with auto save on :-)
```

**Comment by keemor** [comment]
Looks like right now adding only this:
```
 "editor.codeActionsOnSave": {
        "source.fixAll.eslint": true
    },
```
solves the issue

**Comment by feross** [comment]
`autoFixOnSave` works fine for me in the latest version of this plugin. Just make sure that `standard` is installed as a local dependency with `npm install standard --save-dev` in your project.

**Comment by nioposiquit** [comment]
> `autoFixOnSave` works fine for me in the latest version of this plugin. Just make sure that `standard` is installed as a local dependency with `npm install standard --save-dev` in your project.

this works for me installing the `standard` locally but not when I installed it globally even I defined `standard.enableGlobally` to `true`

**Comment by ocroz** [comment]
Same here. I can use `standard --fix` however I install standard locally or globally. But `autoFixOnSave` works only when standard is installed locally. Could this issue be reopened to make this work when standard is installed `globally` too?
Or fix the related issue: https://github.com/standard/vscode-standard/issues/373.

**Comment by ShawnTalbert** [comment]
I haven't had any luck getting this plugin to do anything tangible on typescript code. This is running the latest version of the plugin and vscode as of this comment.

**Comment by edgeorgie** [comment]
Pretty late but just in case...

I got the same issue, this was my solution:

In your settings.json of VSCode:
- Make sure that in your `[javascript]: {...}` config DO NOT have some prettier stuff because you would need to do some extra config with prettier files, etc...

Put this:

`[javascript]": {
        "editor.defaultFormatter": "standard.vscode-standard"
    },`
- Make sure to add or extends _standard_ into your package.json, something like this (remember to install the [ESLint extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) first and as a bonus, the [Stantard's](https://marketplace.visualstudio.com/items?itemName=standard.vscode-standard) too):

```
...
  "eslintConfig": {
    "extends": "standard"
  }
...
```

PLUS: This could be unnecessary but its pretty helpful: `npm install -g standard/semistandard` just in case you love Standard to use it in every project 💖.

**Comment by SteveImmanuel** [comment]
Make sure in your `settings.json`, you **DO NOT** auto-run `onSave` and auto-fix `onSave` like this: 
```
"standard.autoFixOnSave": true,
"standard.run": "onSave",
```
instead, simply use:
```
"standard.autoFixOnSave": true,
"standard.run": "onType",
```

Having them both enabled on save will conflict with one another, preventing the auto-fix to work after you save the file. So, just set the auto-fix `true` and set the auto-run `onType`.

**Comment by aaronmeder** [comment]
> Make sure in your `settings.json`, you **DO NOT** auto-run `onSave` and auto-fix `onSave` like this:

That was it for me, thank you! Auto fixing works for me with only this in my `workspaces .vscode/settings.json`:

```json
{
  "standard.enable": true,
  "standard.autoFixOnSave": true,
}
```
