### ISSUE TITLE
Extension not working if file path contains a folder starting with a dot

### ISSUE THREAD

**Issue by gs71** [standard/vscode-standard#84]
- OS? Windows 10
- StandardJS version? 1.2.3
- VSCode version? 1.32.3
- StandardJS configuration? default
- What do you have in the `OUTPUT` panel?
[Info  - 13:29:29] JavaScript Standard Style server is running.
[Info  - 14:06:14] JavaScript Standard Style library loaded from: ...\AppData\Roaming\npm\node_modules\standard\index.js

Example:
- the extension works on a file D:\Download\test.js
- if I copy the same file to a folder D:\Download\.test\test.js, the extension does not work at all
- same problem if I copy the file to D:\Download\.test\test\test.js or D:\Download\test\.test\test.js

It seems that a "dot folder" anywhere in the path "disables" the estension.

**Comment by theoludwig** [comment]
It seems like it is not anymore the case, i'm inside a folder called `standard.testing` and everything is working properly : 
![2021-02-03_11-20](https://user-images.githubusercontent.com/25207499/106733268-f96bc980-6611-11eb-9774-d12c791b56fc.png)

Please reopen, if the issue appears again, thanks!
