### ISSUE TITLE
Breaks insertFinalNewline

### ISSUE THREAD

**Issue by baelter** [standard/vscode-standard#86]
- StandardJS version? 1.2.0
- VSCode version? 1.34.0
- StandardJS configuration? Default
- What do you have in the `OUTPUT` panel? Nothing

`files.insertFinalNewline` does not work after enabling this extension.

**Comment by theoludwig** [comment]
It is working for me with that configuration : 
```json
{
  "standard.enable": true,
  "files.insertFinalNewline": true
}
```

Re-open if the issue appear again!
