### ISSUE TITLE
Extension doesn't start

### ISSUE THREAD

**Issue by 1valdis** [standard/vscode-standard#88]
- StandardJS version?
12.0.1
- VSCode version?
1.35.1
- StandardJS configuration?
`"javascript.validate.enable": false,`, everything else left as default
- What do you have in the `OUTPUT` panel?
Nothing. I see no signs of `JavaScript Standard Style server is running.` or something like that. Tried to disable all other plugins and clear settings file while leaving only `"javascript.validate.enable": false` - didn't help. I'm on Win10, the extension is installed, the `standard` package is installed globally. I can see that extension doesn't work by simply not following the style rules - I still have empty Problems tab and style errors are not underlined with red color.

**Comment by theoludwig** [comment]
Is it still the case with newer versions ?

**Comment by theoludwig** [comment]
Closing as we need more info, but please reopen, if this issue occurs again. :smile: 
Thanks!
