### ISSUE TITLE
Parsing error: Unexpected token = (ES7 class properties)

### ISSUE THREAD

**Issue by ThomasGoehringer** [standard/vscode-standard#91]
- StandardJS version?
12.0.1

- VSCode version?
1.36.1

- StandardJS configuration?
package.json:
```
"standard": {
    "globals": [
        "localStorage"
    ],
    "parser": "babel-eslint"
}
```

- What do you have in the `OUTPUT` panel?
```
[Info  - 9:55:07 AM] JavaScript Standard Style server is running.
[Info  - 9:55:07 AM] JavaScript Standard Style library loaded from: [path_to_project_root]/node_modules/standard/index.js
```

When I use ES7 class properties (https://borgs.cybrilla.com/tils/es7-class-properties/) standard for VSCode complains about the unexpected token =. When I run standard via `npm run <script-name>` everything works as expected.

I'm using babel-eslint as the parser which was the solution for similar issues.

Here's an example project: https://github.com/ThomasGoehringer/react-course-2-expensify-app
Have a look at AddExpensePage.js for example

**Comment by craigmjackson** [comment]
Also confirmed with:
standard 14.1.0
StandardJS 1.2.0

My context is a react component:
![imagen](https://user-images.githubusercontent.com/8966389/64484221-f4f47480-d1c3-11e9-94bb-6845b08a9f0e.png)

**Comment by feross** [comment]
This is still stage 3 experimental syntax. Please follow the instructions here to enable babel-eslint: https://standardjs.com/#how-do-i-use-experimental-javascript-es-next-features
