### ISSUE TITLE
Feature request: detect engine

### ISSUE THREAD

**Issue by ArmorDarks** [standard/vscode-standard#93]
**What problem do you want to solve?**

In case the project uses semistandard or standardx, it requires additional configuration inside the VS Code. It's against Standard principles.

**What do you think is the correct solution to this problem?**

Detect the engine based on dependencies, unless a `standard.engine` option specified.

**Comment by ArmorDarks** [comment]
Nevermind, #71 already incorporates that feature. My bad.

**Comment by cyrilchapon** [comment]
Hey @ArmorDarks ;

I packaged and installed this last release as suggested in #71 ; but it doesn't detect standardx.
How did you find it auto-detects ?

**Comment by cyrilchapon** [comment]
@chenxsan any idea if that's supposed to work ?
Thanks :)

**Comment by theoludwig** [comment]
Closing as it is a duplicate of #105.
