### ISSUE TITLE
Feature request: Distinguish between errors and warnings

### ISSUE THREAD

**Issue by dkoprowski** [standard/vscode-standard#95]
**What version of this package are you using?**
"standard": "^13.1.0"
vs code extension: 1.2.3
**What problem do you want to solve?**
Styling issues are showed the same way as issues which will break the code execution.
**What do you think is the correct solution to this problem?**
There should me some mechanism to provide an array of rules which may be showed as Warnings instead of Errors. There is similar mechanism in ESLint I guess (although there is only one flag to mark all ESLint complaints as warnings - thats a bit too much, customisable array would be better).
**Are you willing to submit a pull request to implement this change?**
Unfortunately I have no knowledge of developing extensions.

**Comment by feross** [comment]
In `standard` we intentionally treat all issues as errors, with the exception of the new warnings we've introduced for extremely disruptive changes, described here: https://github.com/standard/standard/blob/master/CHANGELOG.md#1601---2020-10-30
