### ISSUE TITLE
Standard engine: Unknown Configuration Setting

### ISSUE THREAD

**Issue by kalber** [standard/vscode-standard#97]
Using standard extension 1.2.3

Version: 1.40.2
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:52:45.129Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.0.0

When I put "standard.engine" in my settings file, it doesn't recognize the setting.
![Captura de Pantalla 2019-12-12 a la(s) 11 43 21](https://user-images.githubusercontent.com/5668893/70735838-a11e8d80-1cd4-11ea-9e21-77d67f0e8250.png)

Someone knows how can I fix it?

Thanks a lot.

**Comment by silasl** [comment]
Has anyone figured out a fix for this issue yet? Contrary to the documentation there seems to be no support for engines other than standard or semistandard.

**Comment by clarkttfu** [comment]
https://github.com/standard/vscode-standardjs/pull/71  has long been merged, I guess the extension in Marketplace is still old?  @fmauNeko

**Comment by fmauNeko** [comment]
Still not published to the Marketplace indeed.

**Comment by clarkttfu** [comment]
Any plan please? 🥺

> Still not published to the Marketplace indeed.

**Comment by fmauNeko** [comment]
Poke @feross @chenxsan

**Comment by Divlo** [comment]
Mainteners of the project is unactive and ignoring issues unfortunately...

**Comment by feross** [comment]
A new version has been published the marketplace! See: https://github.com/standard/vscode-standardjs/issues/121#issuecomment-721937726

Also – if you have skills in TypeScript, please help fix a few issues! https://github.com/standard/vscode-standardjs/issues/131
