### ISSUE TITLE
Proposal Class Fields Support

### ISSUE THREAD

**Issue by maxtomczyk** [standard/vscode-standard#98]
**What version of this package are you using?**
1.2.3

**What problem do you want to solve?**
Support proposal class fields, so Parsing error: Unexpected character '#' will not appear when using private fields as described in https://github.com/tc39/proposal-class-fields

**What do you think is the correct solution to this problem?**
Package will not throw an error when using '#' char in class.

**Are you willing to submit a pull request to implement this change?**
Not sure.

**Comment by feross** [comment]
This is a stage 3 experimental feature, so you need to follow the instructions here to enable support: https://standardjs.com/#how-do-i-use-experimental-javascript-es-next-features
