### ISSUE TITLE
Support for ts-standard

### ISSUE THREAD

**Issue by LinusU** [standard/vscode-standard#99]
**What version of this package are you using?** 1.2.0

**What problem do you want to solve?** I'm moving my code base from JS to TS, and are thus switching from standard to ts-standard.

**What do you think is the correct solution to this problem?** Add ts-standard in the same manor as e.g. standardx

**Are you willing to submit a pull request to implement this change?** Yes

**Comment by theoludwig** [comment]
@LinusU The pull request has been merged successfully but never been published to the VS Code marketplace, can we have an update about that ?

**Comment by feross** [comment]
Please see: https://github.com/standard/vscode-standardjs/issues/121 I need help getting the code on `master` to build successfully so I can publish a new version. PRs welcome!
